### ISSUE TITLE
Unable to create a project using ruby 3.0.0

### ISSUE THREAD

**Issue by pontakornth** [hanami/hanami#1101]
# Issue
I cannot use Ruby 3.0.0 to create a new hanami project. The 2.5.8 is fine.

# Reproduction
1. Use Ruby 3.0.0 with rbenv
2. `gem install hanami`
3. `hanami new bookshelf`
4. The error message should appear.

# Expect behavior
I can create a new project

# Actual behavior
This error message
```
/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/definition.rb:33:in `initialize': wrong number of arguments (given 3, expected 1..2) (ArgumentError)
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/options.rb:17:in `new'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/options.rb:17:in `with'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/builder.rb:59:in `constructor'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/core.rb:41:in `block in <module:Types>'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/core.rb:40:in `each'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/core.rb:40:in `<module:Types>'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/core.rb:4:in `<module:Dry>'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/core.rb:3:in `<top (required)>'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types.rb:158:in `<top (required)>'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/dry-validation-0.11.2/lib/dry/validation/input_processor_compiler.rb:1:in `<top (required)>'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/dry-validation-0.11.2/lib/dry/validation/schema/deprecated.rb:1:in `<top (required)>'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/dry-validation-0.11.2/lib/dry/validation/schema.rb:14:in `<top (required)>'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/dry-validation-0.11.2/lib/dry/validation.rb:39:in `<top (required)>'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/dry-validation-0.11.2/lib/dry-validation.rb:1:in `<top (required)>'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/hanami-validations-1.3.7/lib/hanami/validations.rb:3:in `<top (required)>'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ha
nami-1.3.3/lib/hanami/frameworks.rb:2:in `<top (required)>'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/hanami-1.3.3/lib/hanami.rb:10:in `<module:Hanami>'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/hanami-1.3.3/lib/hanami.rb:8:in `<top (required)>'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/hanami-1.3.3/lib/hanami/cli/commands/command.rb:1:in `<top (required)>'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/hanami-1.3.3/lib/hanami/cli/commands.rb:89:in `<module:Commands>'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/hanami-1.3.3/lib/hanami/cli/commands.rb:56:in `<class:CLI>'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/hanami-1.3.3/lib/hanami/cli/commands.rb:8:in `<module:Hanami>'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/hanami-1.3.3/lib/hanami/cli/commands.rb:4:in `<top (required)>'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/pontakornth/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/hanami-1.3.3/bin/hanami:3:in `<top (required)>'
	from /Users/pontakornth/.rbenv/versions/3.0.0/bin/hanami:23:in `load'
	from /Users/pontakornth/.rbenv/versions/3.0.0/bin/hanami:23:in `<main>'
```

It seems to be issue with `dry-type`.

**Comment by jodosha** [comment]
@pontakornth Sorry but Hanami 1 isn't and will not be compatible with Ruby 3. My apologize, but the effort to make it compatible with 3.0, is invested into creating Hanami 2.0, which is gonna be compatible with Ruby 3.

**Comment by pontakornth** [comment]
@jodosha Thank you for information. I am looking forward to Hanami 2.0. I cannot really contribute the project. I hope you people doing well.
