### ISSUE TITLE
Unable to run application based on Hanami::Model::Error

### ISSUE THREAD

**Issue by ekremkaraca** [hanami/hanami#1103]
I have installed latest version of the hanami, `1.3.4`. I created app with `hanami new bookshelf --database=postgres` command, then installed gem dependencies, then I run command `bundle exec hanami server`. When I open browser & hit `localhost:2300`, I got the error below:

```
Boot Error
Something went wrong while loading /tmp/bookshelf/config.ru

Hanami::Model::Error: undefined method `new' for class `#<Class:BigDecimal>' Did you mean? next
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-model-1.3.2/lib/hanami/model/configuration.rb:161:in `rescue in load!'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-model-1.3.2/lib/hanami/model/configuration.rb:150:in `load!'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-model-1.3.2/lib/hanami/model.rb:80:in `load!'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-1.3.4/lib/hanami/components/components.rb:89:in `block (2 levels) in <module:Components>'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-1.3.4/lib/hanami/components/component.rb:44:in `call'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-1.3.4/lib/hanami/components.rb:108:in `block (2 levels) in resolve'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/map.rb:193:in `block in fetch_or_store'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/map.rb:172:in `fetch'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/map.rb:192:in `fetch_or_store'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-1.3.4/lib/hanami/components.rb:106:in `block in resolve'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-1.3.4/lib/hanami/components.rb:105:in `each'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-1.3.4/lib/hanami/components.rb:105:in `resolve'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-1.3.4/lib/hanami/components/component.rb:144:in `resolve_requirements'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-1.3.4/lib/hanami/components/component.rb:36:in `call'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-1.3.4/lib/hanami/components.rb:108:in `block (2 levels) in resolve'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/map.rb:193:in `block in fetch_or_store'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/map.rb:172:in `fetch'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/map.rb:192:in `fetch_or_store'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-1.3.4/lib/hanami/components.rb:106:in `block in resolve'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-1.3.4/lib/hanami/components.rb:105:in `each'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-1.3.4/lib/hanami/components.rb:105:in `resolve'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-1.3.4/lib/hanami.rb:126:in `boot'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-1.3.4/lib/hanami.rb:151:in `app'
/tmp/bookshelf/config.ru:3:in `block in inner_app'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
/tmp/bookshelf/config.ru:1:in `new'
/tmp/bookshelf/config.ru:1:in `inner_app'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/shotgun-0.9.2/lib/shotgun/loader.rb:113:in `eval'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/shotgun-0.9.2/lib/shotgun/loader.rb:113:in `inner_app'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/shotgun-0.9.2/lib/shotgun/loader.rb:103:in `assemble_app'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/shotgun-0.9.2/lib/shotgun/loader.rb:86:in `proceed_as_child'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/shotgun-0.9.2/lib/shotgun/loader.rb:31:in `call!'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/shotgun-0.9.2/lib/shotgun/loader.rb:18:in `call'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/hanami-1.3.4/lib/hanami/assets/static.rb:49:in `call'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/lint.rb:50:in `_call'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/lint.rb:38:in `call'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/show_exceptions.rb:23:in `call'
/home/ekrem/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
/home/ekrem/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
/home/ekrem/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
/home/ekrem/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'
```

I tried to do it with Ruby `3.0.1` then I realized that the issue #1101, then I tried it with `2.7.2` as it can be seen from log above.

**Comment by adam12** [comment]
Can you share the generated `Gemfile.lock` file?

**Comment by ekremkaraca** [comment]
@adam12 Here you are:

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    better_errors (2.9.1)
      coderay (>= 1.0.0)
      erubi (>= 1.0.0)
      rack (>= 0.9.0)
    binding_of_caller (0.8.0)
      debug_inspector (>= 0.0.1)
    capybara (3.35.3)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    coderay (1.1.3)
    concurrent-ruby (1.1.8)
    debug_inspector (1.1.0)
    diff-lcs (1.4.4)
    dotenv (2.7.6)
    dry-cli (0.6.0)
      concurrent-ruby (~> 1.0)
    dry-configurable (0.12.1)
      concurrent-ruby (~> 1.0)
      dry-core (~> 0.5, >= 0.5.0)
    dry-container (0.7.2)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1, >= 0.1.3)
    dry-core (0.5.0)
      concurrent-ruby (~> 1.0)
    dry-equalizer (0.3.0)
    dry-initializer (1.4.1)
    dry-logic (0.4.2)
      dry-container (~> 0.2, >= 0.2.6)
      dry-core (~> 0.2)
      dry-equalizer (~> 0.2)
    dry-struct (0.3.1)
      dry-configurable (~> 0.1)
      dry-core (~> 0.3)
      dry-equalizer (~> 0.2)
      dry-types (~> 0.9, >= 0.9.0)
      ice_nine (~> 0.11)
    dry-types (0.11.1)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1)
      dry-container (~> 0.3)
      dry-core (~> 0.2, >= 0.2.1)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.4, >= 0.4.0)
      inflecto (~> 0.0.0, >= 0.0.2)
    dry-validation (0.11.0)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1, >= 0.1.3)
      dry-core (~> 0.2, >= 0.2.1)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.4, >= 0.4.0)
      dry-types (~> 0.11.0)
    erubi (1.10.0)
    hanami (1.3.4)
      bundler (>= 1.6, < 3)
      concurrent-ruby (~> 1.0)
      dry-cli (~> 0.5)
      hanami-assets (~> 1.3)
      hanami-controller (~> 1.3)
      hanami-helpers (~> 1.3)
      hanami-mailer (~> 1.3)
      hanami-router (~> 1.3)
      hanami-utils (~> 1.3)
      hanami-validations (>= 1.3, < 3)
      hanami-view (~> 1.3)
    hanami-assets (1.3.5)
      hanami-helpers (~> 1.3)
      hanami-utils (~> 1.3)
      tilt (~> 2.0, >= 2.0.2)
    hanami-controller (1.3.3)
      hanami-utils (~> 1.3)
      rack (~> 2.0)
    hanami-helpers (1.3.3)
      hanami-utils (~> 1.3)
    hanami-mailer (1.3.3)
      hanami-utils (~> 1.3)
      mail (~> 2.6)
      tilt (~> 2.0, >= 2.0.1)
    hanami-model (1.3.2)
      concurrent-ruby (~> 1.0)
      dry-logic (~> 0.4.2, < 0.5)
      dry-types (~> 0.11.0)
      hanami-utils (~> 1.3)
      rom (~> 3.3, >= 3.3.3)
      rom-repository (~> 1.4)
      rom-sql (~> 1.3, >= 1.3.5)
    hanami-router (1.3.2)
      hanami-utils (~> 1.3)
      http_router (= 0.11.2)
      rack (~> 2.0)
    hanami-utils (1.3.8)
      concurrent-ruby (~> 1.0)
      transproc (~> 1.0)
    hanami-validations (1.3.7)
      dry-logic (~> 0.4.2, < 0.5)
      dry-validation (~> 0.11, < 0.12)
      hanami-utils (~> 1.3)
    hanami-view (1.3.3)
      hanami-utils (~> 1.3)
      tilt (~> 2.0, >= 2.0.1)
    hanami-webconsole (0.1.0)
      better_errors (~> 2.4)
      binding_of_caller (~> 0.8)
    http_router (0.11.2)
      rack (>= 1.0.0)
      url_mount (~> 0.2.1)
    ice_nine (0.11.2)
    inflecto (0.0.2)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    mini_mime (1.1.0)
    nokogiri (1.11.3-x86_64-linux)
      racc (~> 1.4)
    pg (1.2.3)
    public_suffix (4.0.6)
    racc (1.5.2)
    rack (2.2.3)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rake (13.0.3)
    regexp_parser (2.1.1)
    rom (3.3.3)
      concurrent-ruby (~> 1.0)
      dry-core (~> 0.3)
      dry-equalizer (~> 0.2)
      dry-initializer (~> 1.3)
      dry-types (~> 0.9, >= 0.9.4)
      rom-mapper (~> 0.5, >= 0.5.1)
    rom-mapper (0.5.1)
      dry-core (~> 0.2, >= 0.2.3)
      dry-equalizer (~> 0.2)
      transproc (~> 1.0)
    rom-repository (1.4.0)
      dry-core (~> 0.3, >= 0.3.1)
      dry-struct (~> 0.3)
      rom (~> 3.3)
      rom-mapper (~> 0.5)
    rom-sql (1.3.5)
      dry-core (~> 0.3)
      dry-equalizer (~> 0.2)
      dry-types (~> 0.11.0)
      rom (~> 3.2, >= 3.2.2)
      sequel (~> 4.43)
    rspec (3.10.0)
      rspec-core (~> 3.10.0)
      rspec-expectations (~> 3.10.0)
      rspec-mocks (~> 3.10.0)
    rspec-core (3.10.1)
      rspec-support (~> 3.10.0)
    rspec-expectations (3.10.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.10.0)
    rspec-mocks (3.10.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.10.0)
    rspec-support (3.10.2)
    sequel (4.49.0)
    shotgun (0.9.2)
      rack (>= 1.0)
    tilt (2.0.10)
    transproc (1.1.1)
    url_mount (0.2.1)
      rack
    xpath (3.2.0)
      nokogiri (~> 1.8)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  capybara
  dotenv (~> 2.4)
  hanami (~> 1.3)
  hanami-model (~> 1.3)
  hanami-webconsole
  pg
  rake
  rspec
  shotgun

BUNDLED WITH
   2.2.16
```

**Comment by adam12** [comment]
Try adding this line to your `Gemfile` then running `bundle`.

```
gem "bigdecimal", "~> 1.4"
```

> I also see so many gems outdated:

Unavoidable, sadly, but fixed in Hanami 2.

**Comment by ekremkaraca** [comment]
@adam12 I directly added `bigdecimal`, still giving error but when I downgraded it to `1.4`, it worked. It was surprising for me. Perhaps you need to add `bigdecimal` as a dependency for hanami `1.x` versions, right?

**Comment by adam12** [comment]
> Perhaps you need to add `bigdecimal` as a dependency for hanami `1.x` versions, right?

The fix is present in `hanami-model`, but it hasn't been released yet.

**Comment by ekremkaraca** [comment]
Thanks again! Assuming the fix is to be released, I'm closing this issue.

**Comment by cllns** [comment]
Here's the relevant PR that fixed it in `hanami/model`: https://github.com/hanami/model/pull/571

**Comment by ekremkaraca** [comment]
@cllns yep, it would work if I change `hanami-model` to:

```
...
gem 'hanami-model', github: 'hanami/model'
...
```
