### ISSUE TITLE
`params` class method in action class raises error due to broken dependency

### ISSUE THREAD

**Issue by mtmtcode** [hanami/hanami#1126]
Recently I started learning Hanami along with [Getting Started](https://guides.hanamirb.org/v1.3/introduction/getting-started/) and ran across an error at "Securing Our Form With Validations" section.

When following  action class was required at testing, `NoMethodError` occured.

```ruby
# apps/web/controllers/books/create.rb
module Web
  module Controllers
    module Books
      class Create
        include Web::Action

        expose :book

        params do
          required(:book).schema do
            required(:title).filled(:str?)
            required(:author).filled(:str?)
          end
        end

        def call(params)
          if params.valid?
            @book = BookRepository.new.create(params[:book])

            redirect_to '/books'
          else
            self.status = 422
          end
        end
      end
    end
  end
end
```

```
An error occurred while loading spec_helper.
Failure/Error: Hanami.boot

NoMethodError:
  undefined method `size' for nil:NilClass
# ./vendor/bundle/ruby/2.7.0/gems/dry-validation-0.11.0/lib/dry/validation/schema/deprecated.rb:11:in `input_processor'
# ./vendor/bundle/ruby/2.7.0/gems/dry-validation-0.11.0/lib/dry/validation/schema/class_interface.rb:165:in `default_options'
# ./vendor/bundle/ruby/2.7.0/gems/dry-validation-0.11.0/lib/dry/validation/schema/class_interface.rb:35:in `new'
# ./vendor/bundle/ruby/2.7.0/gems/hanami-validations-1.3.7/lib/hanami/validations.rb:109:in `validations'
# ./vendor/bundle/ruby/2.7.0/gems/hanami-controller-1.3.3/lib/hanami/action/params.rb:152:in `params'
# ./vendor/bundle/ruby/2.7.0/gems/hanami-controller-1.3.3/lib/hanami/action/validatable.rb:100:in `block in params'
# ./vendor/bundle/ruby/2.7.0/gems/hanami-controller-1.3.3/lib/hanami/action/validatable.rb:100:in `class_eval'
# ./vendor/bundle/ruby/2.7.0/gems/hanami-controller-1.3.3/lib/hanami/action/validatable.rb:100:in `params'
# ./apps/web/controllers/books/create.rb:7:in `<class:Create>'
# ./apps/web/controllers/books/create.rb:4:in `<module:Books>'
# ./apps/web/controllers/books/create.rb:3:in `<module:Controllers>'
# ./apps/web/controllers/books/create.rb:2:in `<module:Web>'
# ./apps/web/controllers/books/create.rb:1:in `<top (required)>'
```

But almost the same action class works fine in [bookshelf example repository](https://github.com/hanami/bookshelf).
After some research, I found out that the difference is due to the version of `dry-configurable`.

`bundle install` now brings `dry-configurable 0.13.0` but it raises the error above.
The version of `dry-configurable` must be `0.12.1` to get Hanami work.

As a workaround, I added following lines to Gemfile and exec `bundle update`.

```
gem "dry-container", "0.8.0"
gem "dry-configurable", "0.12.1"
```

**Comment by jodosha** [comment]
@mtmtcode Thanks for reporting.

To [fix this problem](https://github.com/hanami/validations/pull/221), I had only to pin `dry-configurable` at `<= 0.12`.

Would you please confirm that `dry-container` doesn't require to be specified as dep?
Please remember to remove it from your `Gemfile` and to run a complete `bundle update` and check.

**Comment by mtmtcode** [comment]
@jodosha As you say, the probem has been resolved without pinning `dry-container`.
Thank you for your quick response!
