### ISSUE TITLE
Wrong number of arguments when adding middleware

### ISSUE THREAD

**Issue by paul** [hanami/hanami#1158]
Starting from the Hanami 2.0.0.0.alpha7.1 application template, I added the omniauth middleware in `config/application.rb`:

```ruby
    require "omniauth"
    require "omniauth-slack"
    config.middleware.use OmniAuth::Builder do
      provider :slack, "client_id", "client_secret", scope: "identity.basic"
    end
```

Starting the server blows up with an error:

```
[1741378] ! Unable to load application: ArgumentError: wrong number of arguments (given 2, expected 0..1)
/home/rando/.gem/ruby/3.1.1/gems/rack-2.2.3/lib/rack/builder.rb:123:in `initialize': wrong number of arguments (given 2, expected 0..1) (ArgumentError)
	from /home/rando/.gem/ruby/3.1.1/gems/rack-2.2.3/lib/rack/builder.rb:158:in `new'
	from /home/rando/.gem/ruby/3.1.1/gems/rack-2.2.3/lib/rack/builder.rb:158:in `block in use'
	from /home/rando/.gem/ruby/3.1.1/gems/rack-2.2.3/lib/rack/builder.rb:235:in `block in to_app'
	from /home/rando/.gem/ruby/3.1.1/gems/rack-2.2.3/lib/rack/builder.rb:235:in `each'
	from /home/rando/.gem/ruby/3.1.1/gems/rack-2.2.3/lib/rack/builder.rb:235:in `inject'
	from /home/rando/.gem/ruby/3.1.1/gems/rack-2.2.3/lib/rack/builder.rb:235:in `to_app'
	from /home/rando/.gem/ruby/3.1.1/gems/hanami-2.0.0.alpha7.1/lib/hanami/application/routing/middleware/stack.rb:61:in `to_rack_app'
	from /home/rando/.gem/ruby/3.1.1/gems/hanami-2.0.0.alpha7.1/lib/hanami/application/router.rb:55:in `to_rack_app'
	from /home/rando/.gem/ruby/3.1.1/gems/hanami-2.0.0.alpha7.1/lib/hanami/application.rb:106:in `rack_app'
	from /home/rando/.gem/ruby/3.1.1/gems/hanami-2.0.0.alpha7.1/lib/hanami.rb:43:in `rack_app'
	from config.ru:15:in `block in <main>'
```

It seems like it doesn't like middeware that take blocks for some reason. 

```ruby
# The server starts fine with this
config.middleware.use OmniAuth::Builder

# But it does not with this
config.middleware.use OmniAuth::Builder do
end
```

I added in the debugger, it looks like the omniauth configuration block ends up in `args` instead of `block` in rack/builder.rb:158:

```
[153, 162] in ~/.gem/ruby/3.1.1/gems/rack-2.2.3/lib/rack/builder.rb
   153|       if @map
   154|         mapping, @map = @map, nil
   155|         @use << proc { |app| generate_map(app, mapping) }
   156|       end
   157|       require "debug"
=> 158|       binding.break
   159|       @use << proc { |app| middleware.new(app, *args, &block) }
   160|     end
   161|     ruby2_keywords(:use) if respond_to?(:ruby2_keywords, true)
   162|
=>#0	Rack::Builder#use(middleware=OmniAuth::Builder, args=[#<Proc:0x00007fee3195a098 /home/rando/C..., block=nil) at ~/.gem/ruby/3.1.1/gems/rack-2.2.3/lib/rack/builder.rb:158
  #1	block {|middleware=OmniAuth::Builder, args=[#<Proc:0x00007fee3195a098 /home/rando/C..., blk=nil|} in to_rack_app (4 levels) at ~/.gem/ruby/3.1.1/gems/hanami-2.0.0.alpha7.1/lib/hanami/application/routing/middleware/stack.rb:55
  # and 29 frames (use `bt' command for all frames)
(rdbg) middleware
OmniAuth::Builder
(rdbg) args
[#<Proc:0x00007fee3195a098 /home/rando/Code/textus/flobot2/config/application.rb:16>]
(rdbg) block
nil
```

The `#compact` on [configuration/middleware.rb#L16](https://github.com/hanami/hanami/blob/v2.0.0.alpha7.1/lib/hanami/configuration/middleware.rb#L16) appears to be pushing the `block` argument up a position, then later `*args` destructuring puts it on the wrong place.

```
[12, 21] in ~/.gem/ruby/3.1.1/gems/hanami-2.0.0.alpha7.1/lib/hanami/configuration/middleware.rb
    12|         @stack = []
    13|       end
    14|
    15|       def use(middleware, *args, &block)
    16|         require "debug"
=>  17|         binding.break
    18|         stack.push([middleware, *args, block].compact)
    19|       end
    20|     end
    21|   end
=>#0	Hanami::Configuration::Middleware#use(middleware=OmniAuth::Builder, args=[], block=#<Proc:0x00007f7ff9d3e2a0 /home/rando/Co...) at ~/.gem/ruby/3.1.1/gems/hanami-2.0.0.alpha7.1/lib/hanami/configuration/middleware.rb:17
  #1	<class:Application> at ~/Code/textus/flobot2/config/application.rb:17
  # and 24 frames (use `bt' command for all frames)
(rdbg) middleware
OmniAuth::Builder
(rdbg) args
[]
(rdbg) block
#<Proc:0x00007f7ff9d3e2a0 /home/rando/Code/textus/flobot2/config/application.rb:17>
(rdbg) next    # command
[13, 22] in ~/.gem/ruby/3.1.1/gems/hanami-2.0.0.alpha7.1/lib/hanami/configuration/middleware.rb
    13|       end
    14|
    15|       def use(middleware, *args, &block)
    16|         require "debug"
    17|         binding.break
=>  18|         stack.push([middleware, *args, block].compact)
    19|       end
    20|     end
    21|   end
    22| end
=>#0	Hanami::Configuration::Middleware#use(middleware=OmniAuth::Builder, args=[], block=#<Proc:0x00007f7ff9d3e2a0 /home/rando/Co...) at ~/.gem/ruby/3.1.1/gems/hanami-2.0.0.alpha7.1/lib/hanami/configuration/middleware.rb:18
  #1	<class:Application> at ~/Code/textus/flobot2/config/application.rb:17
  # and 24 frames (use `bt' command for all frames)
(rdbg) stack
[]
(rdbg) next    # command
[14, 22] in ~/.gem/ruby/3.1.1/gems/hanami-2.0.0.alpha7.1/lib/hanami/configuration/middleware.rb
    14|
    15|       def use(middleware, *args, &block)
    16|         require "debug"
    17|         binding.break
    18|         stack.push([middleware, *args, block].compact)
=>  19|       end
    20|     end
    21|   end
    22| end
=>#0	Hanami::Configuration::Middleware#use(middleware=OmniAuth::Builder, args=[], block=#<Proc:0x00007f7ff9d3e2a0 /home/rando/Co...) at ~/.gem/ruby/3.1.1/gems/hanami-2.0.0.alpha7.1/lib/hanami/configuration/middleware.rb:19 #=> [[OmniAuth::Builder, #<Proc:0x00007f7ff9...
  #1	<class:Application> at ~/Code/textus/flobot2/config/application.rb:17
  # and 24 frames (use `bt' command for all frames)
(rdbg) stack
[[OmniAuth::Builder, #<Proc:0x00007f7ff9d3e2a0 /home/rando/Code/textus/flobot2/config/application.rb:17>]]
```

If I remove the `compact`, that alone doesn't help. I can also change my middleware config to `config.middleware.use OmniAuth::Builder, nil do` which gets it closer, but still somewhere in the block destructuring it mangles the args:

```
[50, 59] in ~/.gem/ruby/3.1.1/gems/hanami-2.0.0.alpha7.1/lib/hanami/application/routing/middleware/stack.rb
    50|
    51|             Rack::Builder.new do
    52|               s.each do |prefix, stack|
    53|                 s.mapped(self, prefix) do
    54|                   stack.each do |middleware, *args, blk|
=>  55|                     require "debug"; binding.break if middleware == OmniAuth::Builder
    56|                     use(middleware, *args, &blk)
    57|                   end
    58|                 end
    59|
=>#0	block {|middleware=OmniAuth::Builder, args=[nil, #<Proc:0x00007f80b78763f8 /home/ra..., blk=nil|} in to_rack_app (4 levels) at ~/.gem/ruby/3.1.1/gems/hanami-2.0.0.alpha7.1/lib/hanami/application/routing/middleware/stack.rb:55
  #1	[C] Array#each at ~/.gem/ruby/3.1.1/gems/hanami-2.0.0.alpha7.1/lib/hanami/application/routing/middleware/stack.rb:54
  # and 28 frames (use `bt' command for all frames)
(rdbg) stack
[[#<Dry::Monitor::Rack::Middleware:0x00007f80b6a11150 ...],
 [OmniAuth::Builder, nil, #<Proc:0x00007f80b78763f8 /home/rando/Code/textus/flobot2/config/application.rb:15>, nil],
 [Rack::Session::Cookie, {:key=>"flobot.session", :secret=>"secret", :expire_after=>31536000}, nil]]
```

I tried throwing around some `*args` to no avail, the Ruby 3 changes still confuse me.

**Comment by jodosha** [comment]
@paul This was fixed in 2.0.
