### ISSUE TITLE
Creating a new hanami project with a period in the name breaks require_relative

### ISSUE THREAD

**Issue by Igneous** [hanami/hanami#1163]
```
/tmp ⌚ 3:02:04
$ hanami new company.project
      create  .hanamirc
      create  .env.development
      create  .env.test
      create  README.md
      create  Gemfile
      create  config.ru
      create  config/boot.rb
      create  config/environment.rb
      create  lib/company.project.rb
      create  public/.gitkeep
      create  config/initializers/.gitkeep
      create  lib/company.project/entities/.gitkeep
      create  lib/company.project/repositories/.gitkeep
      create  lib/company.project/mailers/.gitkeep
      create  lib/company.project/mailers/templates/.gitkeep
      create  spec/company.project/entities/.gitkeep
      create  spec/company.project/repositories/.gitkeep
      create  spec/company.project/mailers/.gitkeep
      create  spec/support/.gitkeep
      create  db/migrations/.gitkeep
      create  Rakefile
      create  .rspec
      create  spec/spec_helper.rb
      create  spec/features_helper.rb
      create  spec/support/capybara.rb
      create  db/schema.sql
      create  .gitignore
         run  git init . from "."
      create  apps/web/application.rb
      create  apps/web/config/routes.rb
      create  apps/web/views/application_layout.rb
      create  apps/web/templates/application.html.erb
      create  apps/web/assets/favicon.ico
      create  apps/web/controllers/.gitkeep
      create  apps/web/assets/images/.gitkeep
      create  apps/web/assets/javascripts/.gitkeep
      create  apps/web/assets/stylesheets/.gitkeep
      create  spec/web/features/.gitkeep
      create  spec/web/controllers/.gitkeep
      create  spec/web/views/application_layout_spec.rb
      insert  config/environment.rb
      insert  config/environment.rb
      append  .env.development
      append  .env.test

/tmp ⌚ 3:02:07
$ cd company.project 

/tmp/company.project on  main! ⌚ 3:02:10
$ rbenv local 2.7.4

/tmp/company.project on  main! ⌚ 3:02:18
$ bundle install
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
[snip]
Bundle complete! 9 Gemfile dependencies, 62 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

/tmp/company.project on  main! ⌚ 3:02:26
$ bundle exec hanami routes
bundler: failed to load command: hanami (/home/igneous/.rbenv/versions/2.7.4/bin/hanami)
Traceback (most recent call last):
	24: from /home/igneous/.rbenv/versions/2.7.4/bin/bundle:23:in `<main>'
	23: from /home/igneous/.rbenv/versions/2.7.4/bin/bundle:23:in `load'
	22: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/exe/bundle:36:in `<top (required)>'
	21: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	20: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/exe/bundle:48:in `block in <top (required)>'
	19: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/cli.rb:25:in `start'
	18: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	17: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/cli.rb:31:in `dispatch'
	16: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	15: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	14: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	13: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/cli.rb:483:in `exec'
	12: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:23:in `run'
	11: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
	10: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `load'
	 9: from /home/igneous/.rbenv/versions/2.7.4/bin/hanami:23:in `<top (required)>'
	 8: from /home/igneous/.rbenv/versions/2.7.4/bin/hanami:23:in `load'
	 7: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hanami-1.3.5/bin/hanami:6:in `<top (required)>'
	 6: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/dry-cli-0.7.0/lib/dry/cli.rb:65:in `call'
	 5: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/dry-cli-0.7.0/lib/dry/cli.rb:116:in `perform_registry'
	 4: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hanami-1.3.5/lib/hanami/cli/commands/command.rb:77:in `call'
	 3: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hanami-1.3.5/lib/hanami/environment.rb:410:in `require_application_environment'
	 2: from /home/igneous/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hanami-1.3.5/lib/hanami/environment.rb:410:in `require'
	 1: from /tmp/company.project/config/environment.rb:4:in `<top (required)>'
/tmp/company.project/config/environment.rb:4:in `require_relative': /tmp/company.project/lib/company.project.rb:1: syntax error, unexpected '\\n', expecting '.' or &. or :: or '[' (SyntaxError)
```

Seems like a few things going on here, but ultimately I think it's just acceptable for the scaffolder to remove the period the same as it does with hyphens..

**Comment by adam12** [comment]
Did you want to try your hand at submitting a PR? With all effort going to Hanami 2 at the moment, this might be closed as a `wontfix` otherwise.

**Comment by Igneous** [comment]
Sure I'll give it a shot. Got a couple things in my pipeline this week but can hopefully tackle it this weekend.

**Comment by tak1n** [comment]
> Sure I'll give it a shot. Got a couple things in my pipeline this week but can hopefully tackle it this weekend.

I hope it's okay that I already worked on it. It was quite a minor thing todo actually 😅

**Comment by epitosoft** [comment]
@Igneous we are willing to pay you what you want to complete the project. Please check your email at usleep.

Best regards,
Epitosoft Team
