### ISSUE TITLE
Cannot Create Hanami Project

### ISSUE THREAD

**Issue by Lyriraki** [hanami/hanami#1182]
When i run `hanami new book` i got error like this
```
Traceback (most recent call last):
	48: from /Users/lyriraki/.rbenv/versions/2.7.5/bin/hanami:23:in `<main>'
	47: from /Users/lyriraki/.rbenv/versions/2.7.5/bin/hanami:23:in `load'
	46: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hanami-1.3.5/bin/hanami:3:in `<top (required)>'
	45: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	44: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	43: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hanami-1.3.5/lib/hanami/cli/commands.rb:4:in `<top (required)>'
	42: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hanami-1.3.5/lib/hanami/cli/commands.rb:8:in `<module:Hanami>'
	41: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hanami-1.3.5/lib/hanami/cli/commands.rb:56:in `<class:CLI>'
	40: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hanami-1.3.5/lib/hanami/cli/commands.rb:89:in `<module:Commands>'
	39: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	38: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	37: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hanami-1.3.5/lib/hanami/cli/commands/command.rb:1:in `<top (required)>'
	36: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	35: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	34: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hanami-1.3.5/lib/hanami.rb:8:in `<top (required)>'
	33: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hanami-1.3.5/lib/hanami.rb:10:in `<module:Hanami>'
	32: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	31: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	30: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hanami-1.3.5/lib/hanami/frameworks.rb:2:in `<top (required)>'
	29: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	28: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	27: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hanami-validations-1.3.8/lib/hanami/validations.rb:3:in `<top (required)>'
	26: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	25: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	24: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/dry-validation-0.11.2/lib/dry-validation.rb:1:in `<top (required)>'
	23: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	22: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	21: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/dry-validation-0.11.2/lib/dry/validation.rb:39:in `<top (required)>'
	20: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	19: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	18: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/dry-validation-0.11.2/lib/dry/validation/schema.rb:14:in `<top (required)>'
	17: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	16: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	15: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/dry-validation-0.11.2/lib/dry/validation/schema/deprecated.rb:1:in `<top (required)>'
	14: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	13: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	12: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/dry-validation-0.11.2/lib/dry/validation/input_processor_compiler.rb:1:in `<top (required)>'
	11: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	10: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 9: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/dry-types-0.12.3/lib/dry/types.rb:158:in `<top (required)>'
	 8: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 7: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 6: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/dry-types-0.12.3/lib/dry/types/core.rb:3:in `<top (required)>'
	 5: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/dry-types-0.12.3/lib/dry/types/core.rb:4:in `<module:Dry>'
	 4: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/dry-types-0.12.3/lib/dry/types/core.rb:30:in `<module:Types>'
	 3: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/dry-types-0.12.3/lib/dry/types/core.rb:30:in `each'
	 2: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/dry-types-0.12.3/lib/dry/types/core.rb:31:in `block in <module:Types>'
	 1: from /Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/dry-types-0.12.3/lib/dry/types.rb:67:in `register'
/Users/lyriraki/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/dry-container-0.10.0/lib/dry/container/mixin.rb:151:in `register': undefined method `call' for nil:NilClass (NoMethodError)
```

i use ruby 2.7.5, and this my gem list
```
benchmark (0.2.0, default: 0.1.0)
bigdecimal (3.1.2, default: 2.0.0)
bundler (2.3.17, default: 2.1.4)
cgi (0.3.2, default: 0.1.0.1)
concurrent-ruby (1.1.10)
csv (3.2.3, default: 3.1.2)
date (3.2.2, default: 3.0.3)
dbm (default: 1.1.0)
delegate (0.2.0, default: 0.1.0)
did_you_mean (1.6.1, default: 1.4.0)
digest (3.1.0)
dry-cli (0.7.0)
dry-configurable (0.15.0, 0.12.0)
dry-container (0.10.0)
dry-core (0.7.1)
dry-equalizer (0.3.0)
dry-inflector (0.2.1)
dry-initializer (3.1.1)
dry-logic (1.2.0, 0.4.2)
dry-schema (1.9.3)
dry-types (1.5.1, 0.12.3)
dry-validation (1.8.1, 0.11.2)
etc (1.3.0, default: 1.1.0)
fcntl (1.0.1, default: 1.0.0)
fiddle (1.1.0, default: 1.0.0)
fileutils (1.6.0, default: 1.4.1)
forwardable (1.3.2, default: 1.3.1)
gdbm (default: 2.1.0)
getoptlong (0.1.1, default: 0.1.0)
hanami (1.3.5)
hanami-assets (1.3.5)
hanami-controller (1.3.3)
hanami-helpers (1.3.3)
hanami-mailer (1.3.3)
hanami-router (1.3.2)
hanami-utils (1.3.8)
hanami-validations (1.3.8)
hanami-view (1.3.3)
http_router (0.11.2)
inflecto (0.0.2)
io-console (0.5.11, default: 0.5.6)
ipaddr (1.2.4, default: 1.2.2)
irb (1.4.1, default: 1.2.6)
json (2.6.2, default: 2.3.0)
logger (1.5.1, default: 1.4.2)
mail (2.7.1)
matrix (0.4.2, default: 0.2.0)
mini_mime (1.1.2)
minitest (5.16.2, 5.13.0)
mutex_m (0.1.1, default: 0.1.0)
net-pop (0.1.1, default: 0.1.0)
net-protocol (0.1.3)
net-smtp (0.3.1, default: 0.1.0)
net-telnet (0.2.0)
observer (0.1.1, default: 0.1.0)
open3 (0.1.1, default: 0.1.0)
openssl (3.0.0, default: 2.1.3)
ostruct (0.5.5, default: 0.2.0)
power_assert (2.0.1, 1.1.7)
prime (0.1.2, default: 0.1.1)
pstore (0.1.1, default: 0.1.0)
psych (4.0.4, default: 3.1.0)
racc (1.6.0, default: 1.4.16)
rack (2.2.4)
rake (13.0.6, 13.0.1)
rdoc (6.4.0, default: 6.2.1.1)
readline (0.0.3, default: 0.0.2)
readline-ext (0.1.4, default: 0.1.0)
reline (0.3.1, default: 0.1.5)
rexml (3.2.5, default: 3.2.3.1)
rss (0.2.9, default: 0.2.8)
sdbm (default: 1.0.0)
singleton (0.1.1, default: 0.1.0)
stringio (3.0.2, default: 0.1.0)
strscan (3.0.3, default: 1.0.3)
test-unit (3.5.3, 3.3.4)
tilt (2.0.10)
timeout (0.3.0, default: 0.1.0)
tracer (0.1.1, default: 0.1.0)
transproc (1.1.1)
uri (0.11.0, default: 0.10.0)
url_mount (0.2.1)
webrick (1.7.0, default: 1.6.1)
xmlrpc (0.3.2, 0.3.0)
yaml (0.2.0, default: 0.1.0)
zlib (2.1.1, default: 1.1.0)
```
please help

**Comment by cllns** [comment]
Hi, sorry you ran into this.

I've opened a PR to fix this: https://github.com/hanami/validations/pull/222

**Comment by Lyriraki** [comment]
> Hi, sorry you ran into this.
> 
> I've opened a PR to fix this: [hanami/validations#222](https://github.com/hanami/validations/pull/222)

So, for a while i can't make a project?

**Comment by cllns** [comment]
Here's what you can do to create a project for now:

```
$ gem uninstall dry-container --version 0.10.0
$ gem install dry-container --version 0.9.0
```

Then `hanami new` should work. I just verified it

**Comment by cllns** [comment]
@Lyriraki Sorry you're still running into issues. My previous instructions were incomplete, can you try it again now with the new instructions: https://github.com/hanami/hanami/issues/1182#issuecomment-1181858526?

**Comment by Lyriraki** [comment]
> @Lyriraki Sorry you're still running into issues. My previous instructions were incomplete, can you try it again now with the new instructions: [#1182 (comment)](https://github.com/hanami/hanami/issues/1182#issuecomment-1181858526)?

Now it Works!! thank you
