### ISSUE TITLE
can't create new hanami 1.3.5 project

### ISSUE THREAD

**Issue by senid231** [hanami/hanami#1202]
```
$ rvm use 2.7.6@bookshelf_hanami1 --create
ruby-2.7.6 - #gemset created /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1
ruby-2.7.6 - #generating bookshelf_hanami1 wrappers...........
Using /home/senid/.rvm/gems/ruby-2.7.6 with gemset bookshelf_hanami1

$ gem install bundler
Fetching bundler-2.3.20.gem
Successfully installed bundler-2.3.20
1 gem installed

$ gem install hanami
Fetching dry-cli-0.7.0.gem
Fetching concurrent-ruby-1.1.10.gem
Fetching mini_mime-1.1.2.gem
Fetching transproc-1.1.1.gem
Fetching hanami-helpers-1.3.3.gem
Fetching tilt-2.0.11.gem
Fetching hanami-utils-1.3.8.gem
Fetching hanami-assets-1.3.5.gem
Fetching mail-2.7.1.gem
Fetching dry-core-0.8.1.gem
Fetching hanami-mailer-1.3.3.gem
Fetching hanami-view-1.3.3.gem
Fetching rack-2.2.4.gem
Fetching hanami-controller-1.3.3.gem
Fetching url_mount-0.2.1.gem
Fetching http_router-0.11.2.gem
Fetching hanami-router-1.3.2.gem
Fetching dry-container-0.10.1.gem
Fetching dry-configurable-0.12.0.gem
Fetching dry-equalizer-0.3.0.gem
Fetching hanami-1.3.5.gem
Fetching dry-logic-0.4.2.gem
Fetching inflecto-0.0.2.gem
Fetching dry-types-0.12.3.gem
Fetching dry-validation-0.11.2.gem
Fetching hanami-validations-1.3.8.gem
Successfully installed concurrent-ruby-1.1.10
Successfully installed dry-cli-0.7.0
Successfully installed transproc-1.1.1
Successfully installed hanami-utils-1.3.8
Successfully installed hanami-helpers-1.3.3
Successfully installed tilt-2.0.11
Successfully installed hanami-assets-1.3.5
Successfully installed mini_mime-1.1.2
Successfully installed mail-2.7.1
Successfully installed hanami-mailer-1.3.3
Successfully installed hanami-view-1.3.3
Successfully installed rack-2.2.4
Successfully installed hanami-controller-1.3.3
Successfully installed url_mount-0.2.1
Successfully installed http_router-0.11.2
Successfully installed hanami-router-1.3.2
Successfully installed dry-core-0.8.1
Successfully installed dry-configurable-0.12.0
Successfully installed dry-equalizer-0.3.0
Successfully installed dry-container-0.10.1
Successfully installed dry-logic-0.4.2
Successfully installed inflecto-0.0.2
Successfully installed dry-types-0.12.3
Successfully installed dry-validation-0.11.2
Successfully installed hanami-validations-1.3.8
Successfully installed hanami-1.3.5
26 gems installed

$ hanami new bookshelf --database=postgres
Traceback (most recent call last):
        50: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/bin/ruby_executable_hooks:22:in `<main>'
        49: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/bin/ruby_executable_hooks:22:in `eval'
        48: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/bin/hanami:23:in `<main>'
        47: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/bin/hanami:23:in `load'
        46: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/hanami-1.3.5/bin/hanami:3:in `<top (required)>'
        45: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        44: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        43: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/hanami-1.3.5/lib/hanami/cli/commands.rb:4:in `<top (required)>'
        42: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/hanami-1.3.5/lib/hanami/cli/commands.rb:8:in `<module:Hanami>'
        41: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/hanami-1.3.5/lib/hanami/cli/commands.rb:56:in `<class:CLI>'
        40: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/hanami-1.3.5/lib/hanami/cli/commands.rb:89:in `<module:Commands>'
        39: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        38: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        37: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/hanami-1.3.5/lib/hanami/cli/commands/command.rb:1:in `<top (required)>'
        36: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        35: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        34: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/hanami-1.3.5/lib/hanami.rb:8:in `<top (required)>'
        33: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/hanami-1.3.5/lib/hanami.rb:10:in `<module:Hanami>'
        32: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        31: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        30: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/hanami-1.3.5/lib/hanami/frameworks.rb:2:in `<top (required)>'
        29: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        28: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        27: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/hanami-validations-1.3.8/lib/hanami/validations.rb:3:in `<top (required)>'
        26: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        25: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        24: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/dry-validation-0.11.2/lib/dry-validation.rb:1:in `<top (required)>'
        23: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        22: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        21: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/dry-validation-0.11.2/lib/dry/validation.rb:39:in `<top (required)>'
        20: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        19: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        18: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/dry-validation-0.11.2/lib/dry/validation/schema.rb:14:in `<top (required)>'
        17: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        16: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        15: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/dry-validation-0.11.2/lib/dry/validation/schema/deprecated.rb:1:in `<top (required)>'
        14: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        13: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        12: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/dry-validation-0.11.2/lib/dry/validation/input_processor_compiler.rb:1:in `<top (required)>'
        11: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        10: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         9: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/dry-types-0.12.3/lib/dry/types.rb:158:in `<top (required)>'
         8: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         7: from /home/senid/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         6: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/dry-types-0.12.3/lib/dry/types/core.rb:3:in `<top (required)>'
         5: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/dry-types-0.12.3/lib/dry/types/core.rb:4:in `<module:Dry>'
         4: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/dry-types-0.12.3/lib/dry/types/core.rb:30:in `<module:Types>'
         3: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/dry-types-0.12.3/lib/dry/types/core.rb:30:in `each'
         2: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/dry-types-0.12.3/lib/dry/types/core.rb:31:in `block in <module:Types>'
         1: from /home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/dry-types-0.12.3/lib/dry/types.rb:67:in `register'
/home/senid/.rvm/gems/ruby-2.7.6@bookshelf_hanami1/gems/dry-container-0.10.1/lib/dry/container/mixin.rb:151:in `register': undefined method `call' for nil:NilClass (NoMethodError)
```

**Comment by cllns** [comment]
Sorry about this. We have [a fix merged](https://github.com/hanami/validations/pull/222), it just needs to be released as a new gem version.

In the meantime, can you try the instructions in this comment please? https://github.com/hanami/hanami/issues/1182#issuecomment-1181858526

**Comment by senid231** [comment]
@cllns thanks, I've managed to create project successfully  

```ruby
$ gem uninstall hanami

$ gem uninstall dry-container

$ gem install dry-container --version 0.8.0
Fetching dry-container-0.8.0.gem
Fetching dry-configurable-0.15.0.gem
Fetching dry-core-0.8.1.gem
Fetching concurrent-ruby-1.1.10.gem
Successfully installed concurrent-ruby-1.1.10
Successfully installed dry-core-0.8.1
Successfully installed dry-configurable-0.15.0
Successfully installed dry-container-0.8.00
4 gems installed

$ gem install hanami
Fetching hanami-assets-1.3.5.gem
Fetching mail-2.7.1.gem
Fetching mini_mime-1.1.2.gem
Fetching transproc-1.1.1.gem
Fetching dry-cli-0.7.0.gem
Fetching hanami-helpers-1.3.3.gem
Fetching hanami-utils-1.3.8.gem
Fetching tilt-2.0.11.gem
Fetching hanami-mailer-1.3.3.gem
Fetching hanami-view-1.3.3.gem
Fetching hanami-controller-1.3.3.gem
Fetching url_mount-0.2.1.gem
Fetching http_router-0.11.2.gem
Fetching hanami-router-1.3.2.gem
Fetching dry-equalizer-0.3.0.gem
Fetching dry-configurable-0.12.0.gem
Fetching dry-logic-0.4.2.gem
Fetching rack-2.2.4.gem
Fetching inflecto-0.0.2.gem
Fetching dry-types-0.12.3.gem
Fetching dry-validation-0.11.2.gem
Fetching hanami-1.3.5.gem
Fetching hanami-validations-1.3.9.gem
Successfully installed dry-cli-0.7.0
Successfully installed transproc-1.1.1
Successfully installed hanami-utils-1.3.8
Successfully installed hanami-helpers-1.3.3
Successfully installed tilt-2.0.11
Successfully installed hanami-assets-1.3.5
Successfully installed mini_mime-1.1.2
Successfully installed mail-2.7.1
Successfully installed hanami-mailer-1.3.3
Successfully installed hanami-view-1.3.3
Successfully installed rack-2.2.4
Successfully installed hanami-controller-1.3.3
Successfully installed url_mount-0.2.1
Successfully installed http_router-0.11.2
Successfully installed hanami-router-1.3.2
Successfully installed dry-equalizer-0.3.0
Successfully installed dry-configurable-0.12.0
Successfully installed dry-logic-0.4.2
Successfully installed inflecto-0.0.2
Successfully installed dry-types-0.12.3
Successfully installed dry-validation-0.11.2
Successfully installed hanami-validations-1.3.9
Successfully installed hanami-1.3.5
23 gems installed

$ hanami new bookshelf
      create  .hanamirc
      create  .env.development
      create  .env.test
      create  README.md
      create  Gemfile
      create  config.ru
      create  config/boot.rb
      create  config/environment.rb
      create  lib/bookshelf.rb
      create  public/.gitkeep
      create  config/initializers/.gitkeep
      create  lib/bookshelf/entities/.gitkeep
      create  lib/bookshelf/repositories/.gitkeep
      create  lib/bookshelf/mailers/.gitkeep
      create  lib/bookshelf/mailers/templates/.gitkeep
      create  spec/bookshelf/entities/.gitkeep
      create  spec/bookshelf/repositories/.gitkeep
      create  spec/bookshelf/mailers/.gitkeep
      create  spec/support/.gitkeep
      create  db/migrations/.gitkeep
      create  Rakefile
      create  .rspec
      create  spec/spec_helper.rb
      create  spec/features_helper.rb
      create  spec/support/capybara.rb
      create  db/schema.sql
      create  .gitignore
         run  git init . from "."
      create  apps/web/application.rb
      create  apps/web/config/routes.rb
      create  apps/web/views/application_layout.rb
      create  apps/web/templates/application.html.erb
      create  apps/web/assets/favicon.ico
      create  apps/web/controllers/.gitkeep
      create  apps/web/assets/images/.gitkeep
      create  apps/web/assets/javascripts/.gitkeep
      create  apps/web/assets/stylesheets/.gitkeep
      create  spec/web/features/.gitkeep
      create  spec/web/controllers/.gitkeep
      create  spec/web/views/application_layout_spec.rb
      insert  config/environment.rb
      insert  config/environment.rb
      append  .env.development
      append  .env.test
```

**Comment by cllns** [comment]
hanami-validations 1.3.9 has also been released earlier today, `gem install hanami-validations` should be enough to get `hanami new` working properly again. (As long as you're using the most recently release version, 1.3.5)
