### ISSUE TITLE
On beta `hanami new` - "unitialized constant Dry::System"

### ISSUE THREAD

**Issue by llhhaa** [hanami/hanami#1225]
Hello! My team is giving the Hanami beta a spin, and I am running into a `NameError` when running `hanami new bookshelf`.

```
> gem install hanami --pre                                                                                                                                                        !10131
...
Done installing documentation for zeitwerk, dry-transformer, concurrent-ruby, hanami-utils, dry-inflector, dry-files, dry-cli, bundler, hanami-cli, dry-core, dry-container, dry-configurable, dry-auto_inject, dry-system, dry-events, dry-monitor, hanami after 6 seconds
17 gems installed

> hanami new bookshelf
/Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli/commands/gem/new.rb:61:in `block in run_install_commmand!': hanami install failed (RuntimeError)


"bundler: failed to load command: hanami (/Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bin/hanami)\\n/Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dry-system-0.27.2/lib/dry/system/container.rb:57:in `<class:Container>': uninitialized constant Dry::System::Plugins (NameError)\\n\\n      extend Dry::System::Plugins\\n                        ^^^^^^^^^\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dry-system-0.27.2/lib/dry/system/container.rb:55:in `<module:System>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dry-system-0.27.2/lib/dry/system/container.rb:11:in `<module:Dry>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dry-system-0.27.2/lib/dry/system/container.rb:10:in `<top (required)>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-2.0.0.beta3/lib/hanami/slice.rb:3:in `<top (required)>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-2.0.0.beta3/lib/hanami/app.rb:5:in `require_relative'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-2.0.0.beta3/lib/hanami/app.rb:5:in `<top (required)>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-2.0.0.beta3/lib/hanami.rb:131:in `require_relative'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-2.0.0.beta3/lib/hanami.rb:131:in `<module:Hanami>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-2.0.0.beta3/lib/hanami.rb:8:in `<top (required)>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli/commands/app/routes.rb:3:in `require'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli/commands/app/routes.rb:3:in `<top (required)>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli/commands/app.rb:11:in `require_relative'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli/commands/app.rb:11:in `<module:App>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli/commands/app.rb:6:in `<module:Commands>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli/commands/app.rb:5:in `<module:CLI>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli/commands/app.rb:4:in `<module:Hanami>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli/commands/app.rb:3:in `<top (required)>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli/commands.rb:23:in `require_relative'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli/commands.rb:23:in `register_commands!'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli.rb:14:in `<module:CLI>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli.rb:6:in `<module:Hanami>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli.rb:5:in `<top (required)>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/exe/hanami:5:in `require'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/exe/hanami:5:in `<top (required)>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bin/hanami:25:in `load'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bin/hanami:25:in `<top (required)>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/cli/exec.rb:58:in `load'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/cli/exec.rb:58:in `kernel_load'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/cli/exec.rb:23:in `run'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/cli.rb:486:in `exec'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/cli.rb:31:in `dispatch'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/cli.rb:25:in `start'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/exe/bundle:48:in `block in <top (required)>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/exe/bundle:36:in `<top (required)>'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/bin/bundle:25:in `load'\\n\\tfrom /Users/llhhaa/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'"
        from <internal:kernel>:90:in `tap'
        from /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli/commands/gem/new.rb:60:in `run_install_commmand!'
        from /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli/commands/gem/new.rb:47:in `block (2 levels) in call'
        from /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli/generators/gem/app.rb:21:in `call'
        from /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli/commands/gem/new.rb:44:in `block in call'
        from /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:139:in `chdir'
        from /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:139:in `cd'
        from /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dry-files-0.3.0/lib/dry/files/file_system.rb:190:in `block in chdir'
        from /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dry-files-0.3.0/lib/dry/files/file_system.rb:361:in `with_error_handling'
        from /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dry-files-0.3.0/lib/dry/files/file_system.rb:189:in `chdir'
        from /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dry-files-0.3.0/lib/dry/files.rb:148:in `chdir'
        from /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/lib/hanami/cli/commands/gem/new.rb:43:in `call'
        from /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dry-cli-0.7.0/lib/dry/cli.rb:116:in `perform_registry'
        from /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dry-cli-0.7.0/lib/dry/cli.rb:65:in `call'
        from /Users/llhhaa/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta3/exe/hanami:10:in `<top (required)>'
        from /Users/llhhaa/.rbenv/versions/3.1.2/bin/hanami:25:in `load'
        from /Users/llhhaa/.rbenv/versions/3.1.2/bin/hanami:25:in `<main>'
```

This is on a fresh install of Ruby (via rbenv) and Hanami:
* MacOS: `12.6`
* rbenv: `1.2.0`
* Ruby: `3.1.2p20`
* RubyGems: `3.3.7`
* Hanami: `v2.0.0.beta3`
* `dry-system` is installed at `0.27.2`

Let me know if there is further information I can provide or further triage I can do.

**Comment by solnic** [comment]
Please wait for beta4 that we'll be releasing next week on Monday/Tuesday. It's going to be updated to work with latest dry-rb stuff 🙂

**Comment by llhhaa** [comment]
Got it, thank you!
