### ISSUE TITLE
How do I run all the tests?

### ISSUE THREAD

**Issue by nateberkopec** [hanami/hanami#1288]
As a new contributor, I opened up the directory and ran `bundle exec rake`. This only runs the units tests. OK, no problem, I'll check `rake -T` to look for the task that runs the integration tests.

Hmm, that doesn't exist either. `bundle exec rspec`? Nope, that raises loading errors.

Finally, let's check the github workflow, maybe I'll learn something in there? Nope, it looks like only the unit tests run in CI?

So how do I run the integration tests? 🤔

**Comment by timriley** [comment]
Hey @nateberkopec! Thanks for checking this out :)

We definitely want to make sure it's easy for potential contributors to run the tests.

So I just checked this to confirm, and when I ran `bundle exec rake` on my personal checkout of hanami, here's what I saw:

```shell
$ bundle exec rake
/Users/tim/.asdf/installs/ruby/3.1.2/bin/ruby -I/Users/tim/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib:/Users/tim/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-support-3.12.0/lib /Users/tim/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/exe/rspec spec/integration/action/cookies_spec.rb spec/integration/action/csrf_protection_spec.rb spec/integration/action/format_config_spec.rb spec/integration/action/routes_spec.rb spec/integration/action/sessions_spec.rb spec/integration/action/slice_configuration_spec.rb spec/integration/action/view_integration_spec.rb spec/integration/action/view_rendering/automatic_rendering_spec.rb spec/integration/action/view_rendering/paired_view_inference_spec.rb spec/integration/action/view_rendering_spec.rb spec/integration/code_loading/loading_from_app_spec.rb spec/integration/code_loading/loading_from_lib_spec.rb spec/integration/code_loading/loading_from_slice_spec.rb spec/integration/container/application_routes_helper_spec.rb spec/integration/container/auto_injection_spec.rb spec/integration/container/auto_registration_spec.rb spec/integration/container/autoloader_spec.rb spec/integration/container/imports_spec.rb spec/integration/container/prepare_container_spec.rb spec/integration/container/provider_lifecycle_spec.rb spec/integration/container/shutdown_spec.rb spec/integration/container/standard_providers/rack_provider_spec.rb spec/integration/container/standard_providers_spec.rb spec/integration/dotenv_loading_spec.rb spec/integration/rack_app/body_parser_spec.rb spec/integration/rack_app/middleware_spec.rb spec/integration/rack_app/non_booted_rack_app_spec.rb spec/integration/rack_app/rack_app_spec.rb spec/integration/settings/access_in_slice_class_body_spec.rb spec/integration/settings/access_to_constants_spec.rb spec/integration/settings/loading_from_env_spec.rb spec/integration/settings/settings_component_loading_spec.rb spec/integration/settings/slice_registration_spec.rb spec/integration/settings/using_types_spec.rb spec/integration/setup_spec.rb spec/integration/slices/external_slice_spec.rb spec/integration/slices/slice_configuration_spec.rb spec/integration/slices/slice_loading_spec.rb spec/integration/slices/slice_registrations_spec.rb spec/integration/slices/slice_routing_spec.rb spec/integration/slices_spec.rb spec/integration/view/context/assets_spec.rb spec/integration/view/context/inflector_spec.rb spec/integration/view/context/request_spec.rb spec/integration/view/context/routes_spec.rb spec/integration/view/context/settings_spec.rb spec/integration/view/inflector_spec.rb spec/integration/view/part_namespace_spec.rb spec/integration/view/path_spec.rb spec/integration/view/slice_configuration_spec.rb spec/integration/view/template_spec.rb spec/integration/view/views_spec.rb spec/unit/hanami/config/actions/content_security_policy_spec.rb spec/unit/hanami/config/actions/cookies_spec.rb spec/unit/hanami/config/actions/csrf_protection_spec.rb spec/unit/hanami/config/actions/default_values_spec.rb spec/unit/hanami/config/actions/sessions_spec.rb spec/unit/hanami/config/actions_spec.rb spec/unit/hanami/config/base_url_spec.rb spec/unit/hanami/config/inflector_spec.rb spec/unit/hanami/config/logger_spec.rb spec/unit/hanami/config/router_spec.rb spec/unit/hanami/config/slices_spec.rb spec/unit/hanami/config/views_spec.rb spec/unit/hanami/env_spec.rb spec/unit/hanami/port_spec.rb spec/unit/hanami/settings/env_store_spec.rb spec/unit/hanami/settings_spec.rb spec/unit/hanami/slice_configurable_spec.rb spec/unit/hanami/slice_name_spec.rb spec/unit/hanami/slice_spec.rb spec/unit/hanami/version_spec.rb spec/unit/hanami/web/rack_logger_spec.rb

Randomized with seed 41748
..........................................................................*.......................................................................................................................................................................................................................................................................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Container imports App container is imported into slice containers by default
     # Temporarily skipped with xspecify
     # ./spec/integration/container/imports_spec.rb:4


Finished in 14.31 seconds (files took 0.20259 seconds to load)
402 examples, 0 failures, 1 pending

Randomized with seed 41748
```

RSpec's rake task is our default here, and it prints out the names of all the spec files that it's going to run. It doesn't wrap in that snippet above, but if I paste a reformatter set below, it _looks_ like this includes the integration tests?

```
/Users/tim/.asdf/installs/ruby/3.1.2/bin/ruby -I/Users/tim/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib:/Users/tim/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-support-3.12.0/lib /Users/tim/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/exe/rspec spec/integration/action/cookies_spec.rb
spec/integration/action/csrf_protection_spec.rb
spec/integration/action/format_config_spec.rb
spec/integration/action/routes_spec.rb
spec/integration/action/sessions_spec.rb
spec/integration/action/slice_configuration_spec.rb
spec/integration/action/view_integration_spec.rb
spec/integration/action/view_rendering/automatic_rendering_spec.rb
spec/integration/action/view_rendering/paired_view_inference_spec.rb
spec/integration/action/view_rendering_spec.rb
spec/integration/code_loading/loading_from_app_spec.rb
spec/integration/code_loading/loading_from_lib_spec.rb
spec/integration/code_loading/loading_from_slice_spec.rb
spec/integration/container/application_routes_helper_spec.rb
spec/integration/container/auto_injection_spec.rb
spec/integration/container/auto_registration_spec.rb
spec/integration/container/autoloader_spec.rb
spec/integration/container/imports_spec.rb
spec/integration/container/prepare_container_spec.rb
spec/integration/container/provider_lifecycle_spec.rb
spec/integration/container/shutdown_spec.rb
spec/integration/container/standard_providers/rack_provider_spec.rb
spec/integration/container/standard_providers_spec.rb
spec/integration/dotenv_loading_spec.rb
spec/integration/rack_app/body_parser_spec.rb
spec/integration/rack_app/middleware_spec.rb
spec/integration/rack_app/non_booted_rack_app_spec.rb
spec/integration/rack_app/rack_app_spec.rb
spec/integration/settings/access_in_slice_class_body_spec.rb
spec/integration/settings/access_to_constants_spec.rb
spec/integration/settings/loading_from_env_spec.rb
spec/integration/settings/settings_component_loading_spec.rb
spec/integration/settings/slice_registration_spec.rb
spec/integration/settings/using_types_spec.rb
spec/integration/setup_spec.rb
spec/integration/slices/external_slice_spec.rb
spec/integration/slices/slice_configuration_spec.rb
spec/integration/slices/slice_loading_spec.rb
spec/integration/slices/slice_registrations_spec.rb
spec/integration/slices/slice_routing_spec.rb
spec/integration/slices_spec.rb
spec/integration/view/context/assets_spec.rb
spec/integration/view/context/inflector_spec.rb
spec/integration/view/context/request_spec.rb
spec/integration/view/context/routes_spec.rb
spec/integration/view/context/settings_spec.rb
spec/integration/view/inflector_spec.rb
spec/integration/view/part_namespace_spec.rb
spec/integration/view/path_spec.rb
spec/integration/view/slice_configuration_spec.rb
spec/integration/view/template_spec.rb
spec/integration/view/views_spec.rb
spec/unit/hanami/config/actions/content_security_policy_spec.rb
spec/unit/hanami/config/actions/cookies_spec.rb
spec/unit/hanami/config/actions/csrf_protection_spec.rb
spec/unit/hanami/config/actions/default_values_spec.rb
spec/unit/hanami/config/actions/sessions_spec.rb
spec/unit/hanami/config/actions_spec.rb
spec/unit/hanami/config/base_url_spec.rb
spec/unit/hanami/config/inflector_spec.rb
spec/unit/hanami/config/logger_spec.rb
spec/unit/hanami/config/router_spec.rb
spec/unit/hanami/config/slices_spec.rb
spec/unit/hanami/config/views_spec.rb
spec/unit/hanami/env_spec.rb
spec/unit/hanami/port_spec.rb
spec/unit/hanami/settings/env_store_spec.rb
spec/unit/hanami/settings_spec.rb
spec/unit/hanami/slice_configurable_spec.rb
spec/unit/hanami/slice_name_spec.rb
spec/unit/hanami/slice_spec.rb
spec/unit/hanami/version_spec.rb
spec/unit/hanami/web/rack_logger_spec.rb
```

Would you mind sharing what you see, if it's different to the above?

**Comment by nateberkopec** [comment]
OK, I see now. I think I'll rename the issue: how do I run _all_ the tests locally? It looks like you exclude everything in `isolation`, so how do I run that?

**Comment by nateberkopec** [comment]
Similarly, `script/ci` fails locally for me on the first `isolation` spec:

```
Running: /home/nateberkopec/Code.nosync/upstream/hanami/spec/isolation/hanami/boot/success_spec.rb

An error occurred while loading /home/nateberkopec/Code.nosync/upstream/hanami/spec/isolation/hanami/boot/success_spec.rb.
Failure/Error: slice.config.root ||= root.join(SLICES_DIR, slice_name.to_s)

NoMethodError:
  undefined method `config' for {:namespace=>Web}:Hash
# ./lib/hanami/slice_registrar.rb:138:in `configure_slice'
# ./lib/hanami/slice_registrar.rb:32:in `register'
# ./lib/hanami/slice.rb:395:in `register_slice'
# /home/nateberkopec/Code.nosync/upstream/hanami/spec/isolation/hanami/boot/success_spec.rb:12:in `<top (required)>'
No examples found.

Finished in 0.00002 seconds (files took 2.46 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```
