### ISSUE TITLE
Hanami 2 expects dry logger and generic ruby Logger class doesn't work

### ISSUE THREAD

**Issue by m-dwyer** [hanami/hanami#1295]
# Overview

When creating a new Hanami 2.0.3 application, and registering a logger provider, I am unable to use Ruby's Logger class -- Hanami seems to expect a dry-logger Dispatcher given it attempts to call a `#tagged` method.

# Steps to Reproduce

1. `gem install hanami`
2. `hanami new bookshelf && cd bookshelf`
3. Create a logger provider, using the standard ruby logger:
```
# frozen_string_literal: true

Hanami.app.register_provider :logger do
  start do
    require "logger"
    logger = Logger.new($stdout)

    register "logger", logger
  end
end
```
4. `hanami server`
5. Browse to http://localhost:2300/

The following stack trace now shows:
```
Puma caught this error: undefined method `tagged' for #<Logger:0x000000010328b7f8 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x000000010328b5f0 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x000000010328b3e8 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @binmode=false, @mon_data=#<Monitor:0x000000010328b348>, @mon_data_owner_object_id=4360>>

        logger.tagged(:rack) do
              ^^^^^^^ (NoMethodError)
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-2.0.3/lib/hanami/web/rack_logger.rb:79:in `log_request'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-2.0.3/lib/hanami/web/rack_logger.rb:67:in `block in attach'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/dry-monitor-1.0.1/lib/dry/monitor/notifications.rb:35:in `block in instrument'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/dry-events-1.0.1/lib/dry/events/bus.rb:38:in `block in process'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/dry-events-1.0.1/lib/dry/events/bus.rb:34:in `each'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/dry-events-1.0.1/lib/dry/events/bus.rb:34:in `process'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/dry-events-1.0.1/lib/dry/events/publisher.rb:269:in `process'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/dry-monitor-1.0.1/lib/dry/monitor/notifications.rb:31:in `instrument'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/dry-monitor-1.0.1/lib/dry/monitor/notifications.rb:25:in `stop'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/dry-monitor-1.0.1/lib/dry/monitor/rack/middleware.rb:37:in `call'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-router-2.0.2/lib/hanami/middleware/app.rb:40:in `call'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-2.0.3/lib/hanami/slice.rb:758:in `call'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.1.0/lib/puma/configuration.rb:269:in `call'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.1.0/lib/puma/request.rb:98:in `block in handle_request'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.1.0/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.1.0/lib/puma/request.rb:97:in `handle_request'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.1.0/lib/puma/server.rb:431:in `process_client'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.1.0/lib/puma/server.rb:233:in `block in run'
/Users/em.dwyer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.1.0/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by jodosha** [comment]
@m-dwyer Please review and try https://github.com/hanami/hanami/pull/1352, as it fixes this problem. Thanks!

**Comment by timriley** [comment]
@m-dwyer We've just merged a fix for this, if you'd like to try again :)

Out of interest, would you mind sharing a fuller version (sanitised where necessary) of your logger provider? For the sake of writing useful documentation, we're wondering what you might need to do in the provider that you couldn't so easily do when assigning a logger via app config (e.g. `config.logger = my_logger` inside the app class). Thanks!
