### ISSUE TITLE
Error uploading xlsx file

### ISSUE THREAD

**Issue by candela9** [hanami/hanami#1310]
Puma caught this error: invalid byte sequence in UTF-8 (Rack::QueryParser::InvalidParameterError)

**Comment by timriley** [comment]
Thanks for sharing this, @candela9. This is pretty hard for us to investigation without a proper reproduction, however.

Could you please provide a reproduction app and steps for us to follow?

**Comment by candela9** [comment]
Documents with percent signs report an error when uploading. (%)

**Comment by timriley** [comment]
@candela9 Could you please provide a small hanami app that will let us reproduce this?

**Comment by candela9** [comment]
# Gemfile

source 'https://rubygems.org'

gem 'hanami', '~> 2.0.3'
gem 'hanami-controller', '~> 2.0.2'
gem 'hanami-router', '~> 2.0.2'
gem 'hanami-validations', '~> 2.0.1'
gem "hanami-utils", '~> 2.0.3'

gem 'dry-types', '~> 1.0', '>= 1.6.1'
gem 'puma'
gem 'rake'

**Comment by candela9** [comment]
# Gemfile

source 'https://rubygems.org'

gem 'hanami', '~> 2.0.3'
gem 'hanami-controller', '~> 2.0.2'
gem 'hanami-router', '~> 2.0.2'
gem 'hanami-validations', '~> 2.0.1'
gem "hanami-utils", '~> 2.0.3'

gem 'dry-types', '~> 1.0', '>= 1.6.1'
gem 'puma'
gem 'rake'

**Comment by candela9** [comment]
# File Upload slices

module API
  module Actions
    module Info
      class Upload < API::Action

        def handle(req, res)
          res.body = req.params.to_h
        end

      end
    end
  end
end

**Comment by candela9** [comment]
# routes.rb
slice :api, at: '/api' do
      post "/info/upload", to: "info.upload"
end

**Comment by candela9** [comment]
# 错误
```
Puma caught this error: invalid byte sequence in UTF-8 (Rack::QueryParser::InvalidParameterError)
.rvm/gems/ruby-3.2.2/gems/rack-2.2.6.4/lib/rack/query_parser.rb:90:in `normalize_params'
```

**Comment by candela9** [comment]
# Error
```
Puma caught this error: invalid byte sequence in UTF-8 (Rack::QueryParser::InvalidParameterError)
.rvm/gems/ruby-3.2.2/gems/rack-2.2.6.4/lib/rack/query_parser.rb:90:in `normalize_params'
```

**Comment by candela9** [comment]
# Document content .cvs or .txt at ajax upload
```
1,%
```
## Error content
```
Puma caught this error: invalid %-encoding ("1.txt"
Content-Type: text/plain

1,%
------WebKitFormBoundaryjXQN3qFG6BF9xWq8--
) (Rack::QueryParser::InvalidParameterError)
/home/candela/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/uri/common.rb:370:in `_decode_uri_component'
/home/candela/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/uri/common.rb:338:in `decode_www_form_component'
/home/candela/.rvm/gems/ruby-3.2.2/gems/rack-2.2.6.4/lib/rack/utils.rb:57:in `unescape'
/home/candela/.rvm/gems/ruby-3.2.2/gems/rack-2.2.6.4/lib/rack/query_parser.rb:159:in `unescape'
/home/candela/.rvm/gems/ruby-3.2.2/gems/rack-2.2.6.4/lib/rack/query_parser.rb:73:in `block (2 levels) in parse_nested_query'
/home/candela/.rvm/gems/ruby-3.2.2/gems/rack-2.2.6.4/lib/rack/query_parser.rb:73:in `map!'
/home/candela/.rvm/gems/ruby-3.2.2/gems/rack-2.2.6.4/lib/rack/query_parser.rb:73:in `block in parse_nested_query'
/home/candela/.rvm/gems/ruby-3.2.2/gems/rack-2.2.6.4/lib/rack/query_parser.rb:72:in `each'
/home/candela/.rvm/gems/ruby-3.2.2/gems/rack-2.2.6.4/lib/rack/query_parser.rb:72:in `parse_nested_query'
/home/candela/.rvm/gems/ruby-3.2.2/gems/rack-2.2.6.4/lib/rack/utils.rb:113:in `parse_nested_query'
/home/candela/.rvm/gems/ruby-3.2.2/gems/hanami-router-2.0.2/lib/hanami/router.rb:929:in `_params'
/home/candela/.rvm/gems/ruby-3.2.2/gems/hanami-router-2.0.2/lib/hanami/router.rb:109:in `call'
/home/candela/.rvm/gems/ruby-3.2.2/gems/hanami-router-2.0.2/lib/hanami/middleware/body_parser.rb:52:in `call'
/home/candela/.rvm/gems/ruby-3.2.2/gems/dry-monitor-1.0.1/lib/dry/monitor/rack/middleware.rb:36:in `block in call'
/home/candela/.rvm/gems/ruby-3.2.2/gems/dry-monitor-1.0.1/lib/dry/monitor/clock.rb:15:in `measure'
/home/candela/.rvm/gems/ruby-3.2.2/gems/dry-monitor-1.0.1/lib/dry/monitor/rack/middleware.rb:36:in `call'
/home/candela/.rvm/gems/ruby-3.2.2/gems/hanami-router-2.0.2/lib/hanami/middleware/app.rb:40:in `call'
/home/candela/.rvm/gems/ruby-3.2.2/gems/hanami-2.0.3/lib/hanami/slice.rb:758:in `call'
/home/candela/.rvm/gems/ruby-3.2.2/gems/puma-6.2.2/lib/puma/configuration.rb:270:in `call'
/home/candela/.rvm/gems/ruby-3.2.2/gems/puma-6.2.2/lib/puma/request.rb:98:in `block in handle_request'
/home/candela/.rvm/gems/ruby-3.2.2/gems/puma-6.2.2/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/home/candela/.rvm/gems/ruby-3.2.2/gems/puma-6.2.2/lib/puma/request.rb:97:in `handle_request'
/home/candela/.rvm/gems/ruby-3.2.2/gems/puma-6.2.2/lib/puma/server.rb:431:in `process_client'
/home/candela/.rvm/gems/ruby-3.2.2/gems/puma-6.2.2/lib/puma/server.rb:233:in `block in run'
/home/candela/.rvm/gems/ruby-3.2.2/gems/puma-6.2.2/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by candela9** [comment]
[1.xlsx](https://github.com/hanami/hanami/files/11504056/1.xlsx)
Use this file to upload errors, please help me

**Comment by wuarmin** [comment]
@candela9 I think you have to use the built-in `form`-body parser.

```ruby
use :body_parser, :form
```

**Comment by candela9** [comment]
@wuarmin Thanks, is work.

**Comment by candela9** [comment]
Thanks
