### ISSUE TITLE
Hanami fails out of the box on Windows

### ISSUE THREAD

**Issue by pcopissa** [hanami/hanami#1463]
0) Ruby 3.2.0 on MSYS2 on Windows 10
1) install Hanami as per documentation:
```gem install hanami```
2) try to create a new app as per documentation:
```hanami new  test```
This ends in error:
```
[7932, #<Thread:0x00000132a541a040 run>, #<NoMethodError: undefined method `ignored?' for #<Gem::Specification:0x00000132ac0efc88 @extension_dir=nil, @full_gem_path=nil, @gem_dir=nil, @ignored=nil, @bin_dir=nil, @cache_dir=nil, @cache_file=nil, @doc_dir=nil, @ri_dir=nil, @spec_dir=nil, @spec_file=nil, @gems_dir="C:/Users/pcopissa/.gem/ruby/3.2.0/gems", @base_dir="C:/Users/pcopissa/.gem/ruby/3.2.0", @loaded=false, @activated=false, @loaded_from="C:/Users/pcopissa/.gem/ruby/3.2.0/specifications/dry-logger-1.0.4.gemspec", @original_platform=nil, @installed_by_version=#<Gem::Version "3.4.6">, @autorequire=nil, @date=2024-05-10 00:00:00 UTC, @description="Logging for Ruby", @email=["me@lucaguidi.com", "peter@solnica.online"], @homepage="https://dry-rb.org/gems/dry-logger", @name="dry-logger", @post_install_message=nil, @signing_key=nil, @summary="Logging for Ruby", @version=#<Gem::Version "1.0.4">, @authors=["Luca Guidi", "Peter Solnica"], @bindir="bin", @cert_chain=[], @dependencies=[<Gem::Dependency type=:development name="rspec" requirements=">= 0">], @executables=[], @extensions=[], @extra_rdoc_files=[], @files=[], @licenses=["MIT"], @metadata={"allowed_push_host"=>"https://rubygems.org", "bug_tracker_uri"=>"https://github.com/dry-rb/dry-logger/issues", "changelog_uri"=>"https://github.com/dry-rb/dry-logger/blob/main/CHANGELOG.md", "source_code_uri"=>"https://github.com/dry-rb/dry-logger"}, @platform="ruby", @rdoc_options=[], @require_paths=["lib"], @required_ruby_version=#<Gem::Requirement:0x00000132abf9fef0 @requirements=[[">=", #<Gem::Version "3.0">]]>, @required_rubygems_version=#<Gem::Requirement:0x00000132ab740728 @requirements=[[">=", #<Gem::Version "0">]]>, @requirements=[], @rubygems_version="3.4.6", @specification_version=4, @test_files=[], @new_platform="ruby", @full_name="dry-logger-1.0.4" dry-logger-1.0.4>>, ["c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/specification.rb:2162:in `method_missing'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:273:in `reject'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:273:in `matching_specs'", "c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/dependency.rb:306:in `to_specs'", "c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/specification.rb:1080:in `block in unresolved_specs'", "c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/specification.rb:1080:in `map'", "c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/specification.rb:1080:in `unresolved_specs'", "c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/specification.rb:1058:in `find_in_unresolved'", "<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:104:in `require'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:298:in `<module:Gem>'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:25:in `<top (required)>'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `require_relative'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `<top (required)>'", "<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:99:in `require'", "<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:99:in `require'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/lib/hanami/cli/bundler.rb:3:in `<top (required)>'", "<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:151:in `require'", "<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:151:in `require'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:26:in `require'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/exe/hanami:8:in `<top (required)>'", "C:/Users/pcopissa/AppData/Local/Microsoft/WindowsApps/hanami:32:in `load'", "C:/Users/pcopissa/AppData/Local/Microsoft/WindowsApps/hanami:32:in `<main>'"]]
[7932, #<Thread:0x00000132a541a040 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:170:in `ensure in require'", "<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:170:in `require'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:298:in `<module:Gem>'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:25:in `<top (required)>'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `require_relative'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `<top (required)>'", "<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:99:in `require'", "<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:99:in `require'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/lib/hanami/cli/bundler.rb:3:in `<top (required)>'", "<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:151:in `require'", "<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:151:in `require'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:26:in `require'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/exe/hanami:8:in `<top (required)>'", "C:/Users/pcopissa/AppData/Local/Microsoft/WindowsApps/hanami:32:in `load'", "C:/Users/pcopissa/AppData/Local/Microsoft/WindowsApps/hanami:32:in `<main>'"]]
[7932, #<Thread:0x00000132a541a040 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:170:in `ensure in require'", "<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:170:in `require'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/lib/hanami/cli/bundler.rb:3:in `<top (required)>'", "<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:151:in `require'", "<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:151:in `require'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:26:in `require'", "C:/Users/pcopissa/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/exe/hanami:8:in `<top (required)>'", "C:/Users/pcopissa/AppData/Local/Microsoft/WindowsApps/hanami:32:in `load'", "C:/Users/pcopissa/AppData/Local/Microsoft/WindowsApps/hanami:32:in `<main>'"]]
<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:170:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
        from <internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:170:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:26:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/exe/hanami:8:in `<top (required)>'
        from C:/Users/pcopissa/AppData/Local/Microsoft/WindowsApps/hanami:32:in `load'
        from C:/Users/pcopissa/AppData/Local/Microsoft/WindowsApps/hanami:32:in `<main>'
<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:170:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
        from <internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:170:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/lib/hanami/cli/bundler.rb:3:in `<top (required)>'
        from <internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:151:in `require'
        from <internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:151:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:26:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/exe/hanami:8:in `<top (required)>'
        from C:/Users/pcopissa/AppData/Local/Microsoft/WindowsApps/hanami:32:in `load'
        from C:/Users/pcopissa/AppData/Local/Microsoft/WindowsApps/hanami:32:in `<main>'
<internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:170:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
        from <internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:170:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:298:in `<module:Gem>'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:25:in `<top (required)>'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `require_relative'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `<top (required)>'
        from <internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:99:in `require'
        from <internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:99:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/lib/hanami/cli/bundler.rb:3:in `<top (required)>'
        from <internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:151:in `require'
        from <internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:151:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:26:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/exe/hanami:8:in `<top (required)>'
        from C:/Users/pcopissa/AppData/Local/Microsoft/WindowsApps/hanami:32:in `load'
        from C:/Users/pcopissa/AppData/Local/Microsoft/WindowsApps/hanami:32:in `<main>'
c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/specification.rb:2162:in `method_missing': undefined method `ignored?' for #<Gem::Specification:0x00000132ac0efc88 @extension_dir=nil, @full_gem_path=nil, @gem_dir=nil, @ignored=nil, @bin_dir=nil, @cache_dir=nil, @cache_file=nil, @doc_dir=nil, @ri_dir=nil, @spec_dir=nil, @spec_file=nil, @gems_dir="C:/Users/pcopissa/.gem/ruby/3.2.0/gems", @base_dir="C:/Users/pcopissa/.gem/ruby/3.2.0", @loaded=false, @activated=false, @loaded_from="C:/Users/pcopissa/.gem/ruby/3.2.0/specifications/dry-logger-1.0.4.gemspec", @original_platform=nil, @installed_by_version=#<Gem::Version "3.4.6">, @autorequire=nil, @date=2024-05-10 00:00:00 UTC, @description="Logging for Ruby", @email=["me@lucaguidi.com", "peter@solnica.online"], @homepage="https://dry-rb.org/gems/dry-logger", @name="dry-logger", @post_install_message=nil, @signing_key=nil, @summary="Logging for Ruby", @version=#<Gem::Version "1.0.4">, @authors=["Luca Guidi", "Peter Solnica"], @bindir="bin", @cert_chain=[], @dependencies=[<Gem::Dependency type=:development name="rspec" requirements=">= 0">], @executables=[], @extensions=[], @extra_rdoc_files=[], @files=[], @licenses=["MIT"], @metadata={"allowed_push_host"=>"https://rubygems.org", "bug_tracker_uri"=>"https://github.com/dry-rb/dry-logger/issues", "changelog_uri"=>"https://github.com/dry-rb/dry-logger/blob/main/CHANGELOG.md", "source_code_uri"=>"https://github.com/dry-rb/dry-logger"}, @platform="ruby", @rdoc_options=[], @require_paths=["lib"], @required_ruby_version=#<Gem::Requirement:0x00000132abf9fef0 @requirements=[[">=", #<Gem::Version "3.0">]]>, @required_rubygems_version=#<Gem::Requirement:0x00000132ab740728 @requirements=[[">=", #<Gem::Version "0">]]>, @requirements=[], @rubygems_version="3.4.6", @specification_version=4, @test_files=[], @new_platform="ruby", @full_name="dry-logger-1.0.4" dry-logger-1.0.4> (NoMethodError)
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:273:in `reject'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:273:in `matching_specs'
        from c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/dependency.rb:306:in `to_specs'
        from c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/specification.rb:1080:in `block in unresolved_specs'
        from c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/specification.rb:1080:in `map'
        from c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/specification.rb:1080:in `unresolved_specs'
        from c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/specification.rb:1058:in `find_in_unresolved'
        from <internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:104:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:298:in `<module:Gem>'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:25:in `<top (required)>'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `require_relative'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `<top (required)>'
        from <internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:99:in `require'
        from <internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:99:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/lib/hanami/cli/bundler.rb:3:in `<top (required)>'
        from <internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:151:in `require'
        from <internal:c:/WAMP/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:151:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:26:in `require'
        from C:/Users/pcopissa/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/exe/hanami:8:in `<top (required)>'
        from C:/Users/pcopissa/AppData/Local/Microsoft/WindowsApps/hanami:32:in `load'
        from C:/Users/pcopissa/AppData/Local/Microsoft/WindowsApps/hanami:32:in `<main>'

```

**Comment by pcopissa** [comment]
I suspected that some dependency is causing this issue and removed all versions of ```hanami-*```, ```dry-*``` and reinstalled hanami. Issue is still there. I then removed ```concurrent-ruby 1.2.0```...
At this point ```hanami new test```no longer failed.

It looks like that there is a version number / dependency specification that does not quite work as expected if you install Hanami 2.1.1 on a system where Hanami 2.0 was installed before.

**Comment by pcopissa** [comment]
So to sum it up: 
- installing Hanami 2.1.1 over 2.0 is problematic due to `concurrent-ruby` 1.2.0 being still being used instead of 1.3.4
- an extra (manual) `bundle install` was necessary.
- `bundle exec hanami server` works
- Hanami and/or Ruby makes questionable assumptions about what is considered "executable" on Windows. `NOEXEC` error was solved with creating `dev.bat`.
- `foreman` makes questionable assumptions about the locations of Ruby executable on Windows.
- `foreman` makes questionable assumptions about the `RUBY_PLATFORM` when running on Windows.
- even after fixing all of the above `bundle exec hanami dev` still cannot serve HTML pages.

**Comment by kyleplump** [comment]
hi @pcopissa 👋  thank you for taking the time to investigate this issue so thoroughly!  i'm sure windows users everywhere are thankful for your efforts. i believe we're both working on this issue at the same time and would love to help wherever i can.

i have a few thoughts reading through this:

- i encountered the same issue with `hanami new` generating a `.sh` file instead of `.bat` (or equivalent).  i am struggling to see how we can get around this without detecting platform and creating the appropriate executable type. 
    - on this - i think we need to be careful with 'detecting platform'.  clearly the `foreman` approach of checking 
      `RUBY_PLATFORM` needs updated. alternatively, i suggest using rubygems method directly when detecting OS: 
       `Gem.win_platform?` (https://www.rubydoc.info/github/rubygems/rubygems/Gem.win_platform)
- i do not have a ton of thoughts or suggestions on this foreman stuff yet - i did not encounter it in my own testing.  wielding the knowledge of your new discoveries, i will continue to investigate this.  i'd even be happy to open a PR with them if we can find some solution! 
- i see you opened [#1464](https://github.com/hanami/hanami/issues/1464) - this is the same spot that i got to when testing your proposed solution to https://github.com/hanami/cli/pull/221.  i believe the assets compilation step doesnt work _generally_ (impacting `assets compile`/`assets watch` and things which rely on these, like `hanami dev`), which is another thing blocking the `hanami dev` command from completing.  in the proposed fix (using `respond_to?(:fork)` instead of `NotImplementedError`), when the threads are spawned, they hit an esbuild-plugin error (the `assets.json` file not existing - it actually _does_ exist, but in a different path), and (incorrectly) cleanly exits.  again - still investigating why we end up in this situation where the `assets.json` file is not in the expected location. 

if you'd like to take a stab at detecting the host os and creating the appropriate executable (`.sh` or `.bat`), i can take a look at the foreman issues? once thats all buttoned up, we can move on to the assets bug. if not, no worries! the level of detail in which you lay out the issue is very helpful 😃

**Comment by pcopissa** [comment]
Hi @kyleplump
### About detecting Windows platform
I looked at the code from `Gem.win_platform?()`. It relies on module `RbConfig` which is a file produced by the Ruby interpreter build process and contains a `CONFIG` hash where `CONFIG['host_os']` is a string. On my system it is `mingw32`. `Gem.win_platform?()` then looks for several pattern, one of which is `mingw` to decide the platform is Windows. Other patterns seems to be quite outdated: `djgpp` was a compiler for DOS/Windows XP I played with 20 years ago, IIRC... `bccwin` may well be the Borland C Compiler (even Google does not remember it). `wince` refers to a platform last updated 12 years ago... I note thant there is no reference to Clang compilers and that MSYS2 does support such environments. I just happen to have a Ruby built by somebody that does not use Clang (yet?). Dev at rubyinstaller.org conveivably could change their mind in the future.
In the end, it looks like to me that most (all ?) platform detection code is regexp-based so using one or another is a matter of taste. Depending on `Gem` for this may be a bit of an overkill. I suppose `foreman` may just look at `/bccwin|cygwin|djgpp|mingw|mswin|wince/i.match?(RbConfig::CONFIG['host_os'])`
### About

**Comment by kyleplump** [comment]
👋 @pcopissa 

## detecting windows
this makes sense to me thank you for digging in here!  Even though it seems most platform detection code is using regex, `Gem.win_platform?()` at least gives us more than the aforementioned `foreman` implementation of just matching against `/(win|w)32$/`.  since we would be introducing expanded platform detection into hanami to fix this issue, we have the benefit of doing whatever we want! `win_platform?()` and / or testing against a larger list of `host_os`'s, or both!

also a note on this: it looks like someone already opened a PR w/ foreman for this very issue: https://github.com/ddollar/foreman/pull/799

## `assets.json`
so the file is correctly created after you `&:join` the threads?

re: `favicon.ico` - do you experience the same behavior running `bundle exec hanami assets watch` directly?

i think for the Puma errors on subsequent startup:
`Process.kill` wont work on threads. in the existing 'fork only' implementation, interrups will kill any running child process: 
 https://github.com/hanami/cli/blob/6cfe99705bf949af3342347b234dfc581510c8be/lib/hanami/cli/commands/app/assets/command.rb#L63

the same cannot be said for threads.  we'd need to add in some code to detect if its a full on `process` or a `thread` and call the appropriate `kill` command to shut them down: https://ruby-doc.org/core-2.5.9/Thread.html#method-c-kill

**Comment by pcopissa** [comment]
Sorry but I am now stuck with a non-functional Hanami 2.1 after 2.2 came out (#1470). I am still struggling to get Hanami 2.1 working after the forced upgrade that was foisted on me...

**Comment by pcopissa** [comment]
So I am back with a (mostly) working Hanami 2.1...
@kyleplump
> so the file is correctly created after you &:join the threads?

Yes, `assets.json` was created in the expected location after I added a call to `join`. I suspect that on Windows the main thread terminates before the "asset" thread is run.
However...
`bundle exec hanami assets compile` generates the file `public/assets/assets.json` but **only if** `public/assets` folder already exists. Otherwise I get an error.
On the other hand both `bundle exec hanami assets watch` and `bundle exec hanami dev` behave the same: They generate `public/assets.json` (which is not its expected location if the error message is to be believed) and **only if** `public/assets` folder already exists, another `public/assets/assets.json`.

**Comment by kyleplump** [comment]
👋 

i created a PR which fixes the `assets.json` generation, as well as the `favicon.ico` issue you're experiencing: 
https://github.com/hanami/assets-js/pull/31

i also added a commit to the original PR (https://github.com/hanami/cli/pull/221) which generates a `dev.bat` file when running `hanami new`, and only does this on windows platforms using `Gem.win_platform?`

once these are all settled we can test it all out and see where we need to go from there!

**Comment by dsisnero** [comment]
I have a windows machine - how can I test all these changes?  Also - I know on windows we are usually using the rubyinstaller but I don't know if it includes bash.exe in the %PATH% environment variable.  Can we create a dev.bat that works in the regular cmd shell on windows?

**Comment by dsisnero** [comment]
finally got foreman working with the following in bin\dev.cmd
```
@echo off
  gem list -i foreman --silent && (
        echo Foreman is installed
        foreman start -f Procfile.dev %*
    ) || (
    echo Foreman not installed. Attempting installation...
    call gem install foreman && (
        echo Foreman is installed
        foreman start -f Procfile.dev %*
        )
)
```

**Comment by skidipapo** [comment]
Hello

**Comment by kyleplump** [comment]
hi @dsisnero 👋 

thanks for helping out!  thats a good point about `bash.exe` being in your PATH.  i've added your correct dev implementation to the PR

have you run into any other issues in your testing? specifically around the assets-js package, or spawning new threads for the assets compilation?

**Comment by pcopissa** [comment]
An update about `no asset found for "favicon.ico"` error:
I finally gave a proper look at the stack trace shown when this error occurs: The exception is raised at line 76 in `lib/hanami/assets.rb` when calling `manifest.fetch(path)`: I have :
```>
>> path
=> "favicon.ico"
>> manifest => {
"C:/prj/hanami/test/app/assets/images/favicon.ico"=>
  {"url"=>"/assets/favicon-B8DAB077.ico"
  },
"app.js"=>{"url"=>"/assets/_.._/_.._/app/assets/js/app-HHOJ7CRY.js"},
"app.css"=>{"url"=>"/assets/_.._/_.._/app/assets/js/app-LYGD2ZET.css"}
}
>>
```
I looks like the key for the icon asset inside the `manifest` object was not properly generated somewhere else. Hopefully that info may help you pinpoint what's going on.

**Comment by pcopissa** [comment]
A head up: I updated the conversation https://github.com/hanami/assets-js/pull/31 (improved the proposed modifications and added a proposed fix for `no asset found for "favicon.ico"` ).
