### ISSUE TITLE
Hanami 2.1.1 : Views not working on Windows 

### ISSUE THREAD

**Issue by pcopissa** [hanami/hanami#1464]
0) Installed Hanami 2.1.1 on Ruby 3.2.0 (MSYS2 on Windows 10). See issue #1463 for more context.
1) Created a web app (`bundle exec hanami generate test`) as per documentation.
2) Created a view (as per documentation):
`bundle exec hanami generate action u.v`
```>
Updated config/routes.rb
Created app/actions/u/
Created app/actions/u/v.rb
Created app/views/u/
Created app/views/u/v.rb
Created app/templates/u/
Created app/templates/u/v.html.erb
Created spec/actions/u/v_spec.rb
```
3) run the server (can't use the `dev` environment, see #1463)
`bundle exec hanami server`
4) request the newly added page (```http://localhost:2300/u/v```)
Instead of showing the view, it fails with an error: 
_Hanami::Assets::ManifestMissingError at /u/v
Missing manifest file at "C:/prj/hanami/test/public/assets/assets.json"
Have you run `hanami assets compile` or `hanami assets watch`?_

My understanding (maybe that's a misunderstanding ?) is that I should get the HTML defined in `C:/prj/hanami/test/app/templates/u/v.html.erb)`

However, if I manually execute the suggest command:
`bundle exec hanami assets compile`
I get an error:
```>
C:/Users/frobert/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/lib/hanami/cli/commands/app/assets/command.rb:85:in `fork': fork() function is unimplemented on this machine (NotImplementedError)
        from C:/Users/frobert/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/lib/hanami/cli/commands/app/assets/command.rb:85:in `fork_child_assets_command'
        from C:/Users/frobert/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/lib/hanami/cli/commands/app/assets/command.rb:61:in `block in call'
        from C:/Users/frobert/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/lib/hanami/cli/commands/app/assets/command.rb:61:in `map'
        from C:/Users/frobert/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/lib/hanami/cli/commands/app/assets/command.rb:61:in `call'
        from C:/Users/frobert/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/lib/hanami/cli/commands/app/command.rb:40:in `call'
        from C:/Users/frobert/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/lib/hanami/cli/commands/app/command.rb:40:in `call'
        from C:/Users/frobert/.gem/ruby/3.2.0/gems/dry-cli-1.2.0/lib/dry/cli.rb:117:in `perform_registry'
        from C:/Users/frobert/.gem/ruby/3.2.0/gems/dry-cli-1.2.0/lib/dry/cli.rb:66:in `call'
        from C:/Users/frobert/.gem/ruby/3.2.0/gems/hanami-cli-2.1.1/exe/hanami:11:in `<top (required)>'
        from C:/Users/frobert/AppData/Local/Microsoft/WindowsApps/hanami:32:in `load'
        from C:/Users/frobert/AppData/Local/Microsoft/WindowsApps/hanami:32:in `<main>'
```
I believe a similar problem was reported for Hanami 2.2 (https://github.com/hanami/cli/pull/221)

**Comment by pcopissa** [comment]
Update: I looked up the proposed solution for the `NotImplementedError`, tried it and it failed. 

Found an alternative fix that does not crash `bundle exec hanami assets compile` and ran it.

Fetched the page again. Error is still there. No `public/assets.json` file exists.
