### ISSUE TITLE
Error on deploy "bookshelf" with rspec to heroku

### ISSUE THREAD

**Issue by vyper** [hanami/hanami#495]
I used the commands based in main page:

```bash
gem install hanami # installed 0.7.1
hanami new bookshelf --test=rspec
cd bookshelf && bundle
# added this file
echo 'body { background-color: #ccc; }' >  apps/web/assets/stylesheets/application.css
git add . && git commit -m "Initial commit"
heroku apps:create
heroku config:add BOOKSHELF_DATABASE_URL="file:///db/bookshelf"
heroku config:add HANAMI_ENV=production
git push heroku master # here, the error
```

# Error
```
[...]
remote: -----> Writing config/database.yml to read from DATABASE_URL
remote:        Could not detect rake tasks
remote:        ensure you can run `$ bundle exec rake -P` against your app with no environment variables present
remote:        and using the production group of your Gemfile.
remote:        rake aborted!
remote:        LoadError: cannot load such file -- rspec/core/rake_task
remote:        /tmp/build_ac7604013813153e87aa6e06f7e07536/Rakefile:3:in `require'
remote:        /tmp/build_ac7604013813153e87aa6e06f7e07536/Rakefile:3:in `<top (required)>'
remote:        /tmp/build_ac7604013813153e87aa6e06f7e07536/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load'
remote:        /tmp/build_ac7604013813153e87aa6e06f7e07536/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load_rakefile'
remote:        /tmp/build_ac7604013813153e87aa6e06f7e07536/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:689:in `raw_load_rakefile'
remote:        /tmp/build_ac7604013813153e87aa6e06f7e07536/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:94:in `block in load_rakefile'
remote:        /tmp/build_ac7604013813153e87aa6e06f7e07536/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
remote:        /tmp/build_ac7604013813153e87aa6e06f7e07536/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:93:in `load_rakefile'
remote:        /tmp/build_ac7604013813153e87aa6e06f7e07536/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:77:in `block in run'
remote:        /tmp/build_ac7604013813153e87aa6e06f7e07536/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
remote:        /tmp/build_ac7604013813153e87aa6e06f7e07536/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
remote:        /tmp/build_ac7604013813153e87aa6e06f7e07536/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
remote:        vendor/bundle/bin/rake:16:in `load'
remote:        vendor/bundle/bin/rake:16:in `<main>'
remote:
remote: ###### WARNING:
remote:        You have not declared a Ruby version in your Gemfile.
[...]
```

And to fix this I changed `Rakefile`:

# From
```
require 'rake'
require 'hanami/rake_tasks'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec)
task default: :spec
```

# To
```
require 'rake'
require 'hanami/rake_tasks'

 # Does not use rspec in production
if ENV['HANAMI_ENV'] != 'production'
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec)
  task default: :spec
end
```

**Comment by hlegius** [comment]
Hello @vyper! Thanks for reporting this one. :100: 

I've just double checked here and you're right. Let's wait @jodosha to see how to proceed.

**Comment by joneslee85** [comment]
good spot, I think we should change the logic to check if the class constant exists or not rather than checking the env

**Comment by vyper** [comment]
@joneslee85 but error occurred in `require`. I tried think for another solution...

**Comment by joneslee85** [comment]
@vyper 

```
begin
  require 'rspec/core/rake_task'
  RSpec::Core::RakeTask.new(:spec)
rescue LoadError
end
```

**Comment by vyper** [comment]
I'll try fix this! (;
