### ISSUE TITLE
Error on `rake test`

### ISSUE THREAD

**Issue by ericfreese** [hanami/hanami#570]
So I've just started the ["Getting Started" guide](http://hanamirb.org/guides/getting-started/). I created a new project, created a new test, and running `bundle exec rake test` spits out a bunch of errors:

```
$ hanami version
v0.7.2
$ hanami new bookshelf --database=postgres
      create  .hanamirc
      create  .env
      create  .env.development
      create  .env.test
      create  Gemfile
      create  config.ru
      create  config/environment.rb
      create  lib/bookshelf.rb
      create  lib/config/mapping.rb
      create  public/.gitkeep
      create  config/initializers/.gitkeep
      create  lib/bookshelf/entities/.gitkeep
      create  lib/bookshelf/repositories/.gitkeep
      create  lib/bookshelf/mailers/.gitkeep
      create  lib/bookshelf/mailers/templates/.gitkeep
      create  spec/bookshelf/entities/.gitkeep
      create  spec/bookshelf/repositories/.gitkeep
      create  spec/bookshelf/mailers/.gitkeep
      create  spec/support/.gitkeep
      create  db/migrations/.gitkeep
      create  Rakefile
      create  spec/spec_helper.rb
      create  spec/features_helper.rb
      create  db/schema.sql
      create  .gitignore
         run  git init . from "."
      create  apps/web/application.rb
      create  apps/web/config/routes.rb
      create  apps/web/views/application_layout.rb
      create  apps/web/templates/application.html.erb
      create  apps/web/assets/favicon.ico
      create  apps/web/controllers/.gitkeep
      create  apps/web/assets/images/.gitkeep
      create  apps/web/assets/javascripts/.gitkeep
      create  apps/web/assets/stylesheets/.gitkeep
      create  spec/web/features/.gitkeep
      create  spec/web/controllers/.gitkeep
      create  spec/web/views/.gitkeep
      insert  config/environment.rb
      insert  config/environment.rb
      append  .env.development
      append  .env.test
$ cd bookshelf
$ bundle install
Using rake 11.1.2
Using addressable 2.4.0
Using mime-types-data 3.2016.0221
Using mini_portile2 2.0.0
Using rack 1.6.4
Using dotenv 2.1.1
Using bundler 1.12.3
Using hanami-utils 0.7.1
Using tilt 2.0.3
Using thor 0.19.1
Using sequel 4.34.0
Using minitest 5.8.4
Using pg 0.18.4
Using mime-types 3.0
Using nokogiri 1.6.7.2
Using rack-test 0.6.3
Using url_mount 0.2.1
Using shotgun 0.9.1
Using hanami-helpers 0.3.0
Using hanami-validations 0.5.0
Using hanami-view 0.6.1
Using hanami-model 0.6.1
Using mail 2.6.4
Using xpath 2.0.0
Using http_router 0.11.2
Using hanami-assets 0.2.1
Using hanami-controller 0.6.1
Using hanami-mailer 0.2.0
Using capybara 2.7.1
Using hanami-router 0.6.2
Using hanami 0.7.2
Bundle complete! 7 Gemfile dependencies, 31 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
$ vi spec/web/features/visit_home_spec.rb
$ cat spec/web/features/visit_home_spec.rb
require 'features_helper'

describe 'Visit home' do
  it 'is successful' do
    visit '/'

    page.body.must_include('Bookshelf')
  end
end
$ bundle exec rake test
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-utils-0.7.1/lib/hanami/utils/class_attribute.rb:67: warning: `*' interpreted as argument prefix
/Users/ericfreese/.gem/ruby/2.2.4/gems/url_mount-0.2.1/lib/url_mount.rb:55: warning: method redefined; discarding old variables
/Users/ericfreese/.gem/ruby/2.2.4/gems/url_mount-0.2.1/lib/url_mount.rb:27: warning: previous definition of variables was here
/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router/route.rb:10: warning: method redefined; discarding old match_partially
/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router/route.rb:10: warning: method redefined; discarding old router
/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router/generator.rb:58: warning: assigned but unused variable - generator
/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router/route_helper.rb:99: warning: assigned but unused variable - params
/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router/route_helper.rb:84: warning: method redefined; discarding old options
/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router/route_helper.rb:84: warning: previous definition of options was here
/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router.rb:113: warning: method redefined; discarding old options
/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router.rb:113: warning: previous definition of options was here
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-router-0.6.2/lib/hanami/routing/force_ssl.rb:130: warning: private attribute?
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-utils-0.7.1/lib/hanami/utils/path_prefix.rb:143: warning: private attribute?
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-view-0.6.1/lib/hanami/presenter.rb:1: warning: loading in progress, circular require considered harmful - /Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-view-0.6.1/lib/hanami/view/escape.rb
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:4:in  `<main>'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:4:in  `select'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:9:in  `block in <main>'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:9:in  `each'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:10:in  `block (2 levels) in <main>'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:10:in  `require'
	from /Users/ericfreese/Code/hanami/bookshelf/spec/web/features/visit_home_spec.rb:1:in  `<top (required)>'
	from /Users/ericfreese/Code/hanami/bookshelf/spec/web/features/visit_home_spec.rb:1:in  `require'
	from /Users/ericfreese/Code/hanami/bookshelf/spec/features_helper.rb:2:in  `<top (required)>'
	from /Users/ericfreese/Code/hanami/bookshelf/spec/features_helper.rb:2:in  `require_relative'
	from /Users/ericfreese/Code/hanami/bookshelf/spec/spec_helper.rb:4:in  `<top (required)>'
	from /Users/ericfreese/Code/hanami/bookshelf/spec/spec_helper.rb:4:in  `require_relative'
	from /Users/ericfreese/Code/hanami/bookshelf/config/environment.rb:3:in  `<top (required)>'
	from /Users/ericfreese/Code/hanami/bookshelf/config/environment.rb:3:in  `require'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/setup.rb:1:in  `<top (required)>'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/setup.rb:1:in  `require'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami.rb:2:in  `<top (required)>'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami.rb:2:in  `require'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/application.rb:2:in  `<top (required)>'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/application.rb:2:in  `require'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/frameworks.rb:2:in  `<top (required)>'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/frameworks.rb:2:in  `require'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-view-0.6.1/lib/hanami/view.rb:8:in  `<top (required)>'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-view-0.6.1/lib/hanami/view.rb:8:in  `require'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-view-0.6.1/lib/hanami/view/escape.rb:2:in  `<top (required)>'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-view-0.6.1/lib/hanami/view/escape.rb:2:in  `require'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-view-0.6.1/lib/hanami/presenter.rb:1:in  `<top (required)>'
	from /Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-view-0.6.1/lib/hanami/presenter.rb:1:in  `require'
(eval):2: warning: method redefined; discarding old link
(eval):2: warning: previous definition of link was here
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/loader.rb:39: warning: private attribute?
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/loader.rb:39: warning: private attribute?
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-view-0.6.1/lib/hanami/view/dsl.rb:317: warning: instance variable @layout not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/capybara-2.7.1/lib/capybara.rb:395: warning: method redefined; discarding old reuse_server=
/Users/ericfreese/.gem/ruby/2.2.4/gems/capybara-2.7.1/lib/capybara/session.rb:741: warning: assigned but unused variable - path
/Users/ericfreese/.gem/ruby/2.2.4/gems/sequel-4.34.0/lib/sequel/dataset.rb:42: warning: private attribute?
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/configuration.rb:420: warning: instance variable @assets not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/configuration.rb:895: warning: instance variable @adapter not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/configuration.rb:850: warning: instance variable @mapping not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/configuration.rb:951: warning: instance variable @default_request_format not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/configuration.rb:1006: warning: instance variable @default_response_format not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/configuration.rb:122: warning: instance variable @force_ssl not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/configuration.rb:1182: warning: instance variable @port not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/configuration.rb:1708: warning: instance variable @path_prefix not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/configuration.rb:1694: warning: instance variable @logger not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/configuration.rb:1182: warning: instance variable @port not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/configuration.rb:1708: warning: instance variable @path_prefix not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/configuration.rb:122: warning: instance variable @force_ssl not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router.rb:248: warning: instance variable @compiled not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-assets-0.2.1/lib/hanami/assets/configuration.rb:117: warning: instance variable @digest not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router.rb:248: warning: instance variable @compiled not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/configuration.rb:1182: warning: instance variable @port not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-0.7.2/lib/hanami/configuration.rb:122: warning: instance variable @force_ssl not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router.rb:248: warning: instance variable @compiled not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-assets-0.2.1/lib/hanami/assets/configuration.rb:117: warning: instance variable @digest not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router.rb:248: warning: instance variable @compiled not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router/route_helper.rb:22: warning: instance variable @name not initialized
Run options: --seed 46486

# Running:

/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router.rb:294: warning: instance variable @compiled not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router.rb:248: warning: instance variable @compiled not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router/request.rb:10:in `initialize': warning: URI.unescape is obsolete
/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router.rb:294: warning: instance variable @compiled not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/http_router-0.11.2/lib/http_router/request.rb:10:in `initialize': warning: URI.unescape is obsolete
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-controller-0.6.1/lib/hanami/action/mime.rb:195: warning: instance variable @content_type not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-controller-0.6.1/lib/hanami/action/mime.rb:249: warning: instance variable @charset not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-controller-0.6.1/lib/hanami/action/mime.rb:195: warning: instance variable @content_type not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-controller-0.6.1/lib/hanami/action/head.rb:61: warning: instance variable @_status not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-controller-0.6.1/lib/hanami/action/rack.rb:140: warning: instance variable @_status not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-controller-0.6.1/lib/hanami/action/rack.rb:140: warning: instance variable @_body not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-controller-0.6.1/lib/hanami/action/mime.rb:195: warning: instance variable @content_type not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-controller-0.6.1/lib/hanami/action/head.rb:61: warning: instance variable @_status not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-controller-0.6.1/lib/hanami/action/glue.rb:62: warning: instance variable @_body not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-controller-0.6.1/lib/hanami/action/glue.rb:41: warning: instance variable @_status not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-view-0.6.1/lib/hanami/view/dsl.rb:79: warning: instance variable @format not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-view-0.6.1/lib/hanami/view/dsl.rb:79: warning: instance variable @format not initialized
/Users/ericfreese/.gem/ruby/2.2.4/gems/hanami-view-0.6.1/lib/hanami/view/rendering/scope.rb:79: warning: instance variable @view not initialized
F

Finished in 0.030069s, 33.2573 runs/s, 66.5147 assertions/s.

  1) Failure:
Visit home#test_0001_is successful [/Users/ericfreese/Code/hanami/bookshelf/spec/web/features/visit_home_spec.rb:7]:
Expected "<!DOCTYPE html>\n<html>\n  <head>\n    <title>Not Found</title>\n  </head>\n  <body>\n    <h1>Not Found</h1>\n  </body>\n</html>\n" to include "Bookshelf".

1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -w -I"lib:spec" -I"/Users/ericfreese/.gem/ruby/2.2.4/gems/rake-11.1.2/lib" "/Users/ericfreese/.gem/ruby/2.2.4/gems/rake-11.1.2/lib/rake/rake_test_loader.rb" "spec/**/*_spec.rb" ]
/Users/ericfreese/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `load'
/Users/ericfreese/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/ericfreese/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:24:in `run'
/Users/ericfreese/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli.rb:304:in `exec'
/Users/ericfreese/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/ericfreese/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/ericfreese/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/ericfreese/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/ericfreese/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli.rb:11:in `start'
/Users/ericfreese/.gem/ruby/2.2.4/gems/bundler-1.12.3/exe/bundle:27:in `block in <top (required)>'
/Users/ericfreese/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/Users/ericfreese/.gem/ruby/2.2.4/gems/bundler-1.12.3/exe/bundle:19:in `<top (required)>'
/Users/ericfreese/.gem/ruby/2.2.4/bin/bundle:23:in `load'
/Users/ericfreese/.gem/ruby/2.2.4/bin/bundle:23:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

What am I missing here?

**Comment by ericfreese** [comment]
Nevermind, I see this has been reported over in the `utils` project: https://github.com/hanami/utils/issues/123
