### ISSUE TITLE
Hanami not configured error in app mode

### ISSUE THREAD

**Issue by spectator** [hanami/hanami#714]
Hi,

I'm starting new Hanami project for very basic JSON API app and running into an issue using Application architecture versus Container. Here is my steps

```
ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
```

```
hanami --version
v0.9.2
```

(also tried `--hanami-head=true` with the same results)

```
hanami new msa --arch=app
```

```
cd msa
bundle
```

[Gemfile.lock](https://gist.github.com/spectator/6591cd5672f883ab0208912fef83e71c)

```
hanami server
/Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/hanami-0.9.2/lib/hanami.rb:75:in `block in configuration': Hanami not configured (RuntimeError)
	from /Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/hanami-0.9.2/lib/hanami.rb:74:in `synchronize'
	from /Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/hanami-0.9.2/lib/hanami.rb:74:in `configuration'
	from /Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/hanami-0.9.2/lib/hanami/commands/command.rb:44:in `initialize'
	from /Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/hanami-0.9.2/lib/hanami/commands/server.rb:13:in `initialize'
	from /Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/hanami-0.9.2/lib/hanami/cli.rb:46:in `new'
	from /Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/hanami-0.9.2/lib/hanami/cli.rb:46:in `server'
	from /Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/hanami-0.9.2/bin/hanami:5:in `<top (required)>'
	from /Users/user/.rbenv/versions/2.4.0/bin/hanami:22:in `load'
	from /Users/user/.rbenv/versions/2.4.0/bin/hanami:22:in `<main>'
```

Exactly the same steps but using Container architecture (w/o `--arch` argument) works just fine.

Please let me know if I can provide any more details.

**Comment by jodosha** [comment]
@spectator Hi, I'm sorry we removed support for the `app` architecture as of 0.9.0. https://github.com/hanami/hanami/blob/master/CHANGELOG.md#changed

**Comment by spectator** [comment]
Ah! Sorry, I missed that. Hanamirb.org guides still have mentions of that.

**Comment by jodosha** [comment]
@spectator where exactly? can you please link them here? they are leftovers.

**Comment by spectator** [comment]
@jodosha here is a few places in guides

http://hanamirb.org/guides/command-line/applications/#architecture
http://hanamirb.org/guides/command-line/destroy/#actions

CLI help also has mentions

```
hanami new --help
Usage:
  hanami new PROJECT_NAME

Options:
  -d, --db, [--database=DATABASE]                        # Application database (mysql/mysql2/postgresql/postgres/sqlite/sqlite3)
                                                         # Default: sqlite
  -a, --arch, [--architecture=ARCHITECTURE]              # Project architecture (container/app)
                                                         # Default: container
          [--application-name=APPLICATION_NAME]          # Application name, only for container
                                                         # Default: web
          [--application-base-url=APPLICATION_BASE_URL]  # Application base url
                                                         # Default: /
          [--template=TEMPLATE]                          # Template engine (erb/haml/slim)
                                                         # Default: erb
          [--test=TEST]                                  # Project test framework (minitest/rspec)
                                                         # Default: minitest
          [--hanami-head], [--no-hanami-head]            # Use hanami HEAD (true/false)
          [--help=HELP]                                  # Displays the usage method

Description:
  `hanami new` creates a new hanami project. You can specify various options such as the database to be used as well as the path and architecture.

  $ > hanami new fancy_app --application_name=admin

  $ > hanami new fancy_app --arch=app

  $ > hanami new fancy_app --hanami-head=true
```

**Comment by spectator** [comment]
Also some assertions in the code https://github.com/hanami/hanami/blob/master/lib/hanami/commands/new/abstract.rb#L119-L123
