### ISSUE TITLE
Module loading issue

### ISSUE THREAD

**Issue by nickgnd** [hanami/hanami#732]
Hi everyone and before all thanks for your great work and effort! 
Today I was playing with a Hanami and I noticed a strange behavior on how Hanami load files. More precisely, when I try to start the console/server or launch the test suite I get the error `NameError: uninitialized constant Web::Controllers::Sessions::Create::JwtHelper`. The error is raised by the action `sessions#create`.

After a quick debug, I think the error depends on how Hanami load the files in [alphabetical order](https://github.com/hanami/utils/blob/master/lib/hanami/utils/file_list.rb).
In fact, If an action mixin a module which:
- is located in the same path
- its name begins with a letter that comes next the start letter of the action name in the alphabet

the action is loaded before the module and the error `NameError: uninitialized constant` is raised.

For Example:

```ruby
# apps/web/controllers/sessions/create.rb
module Web
  module Controllers
    module Sessions
      class Create
        include Web::Action
        include JwtHeper
       
        # ...
      end
    end
  end
end
```

```ruby
# apps/web/controllers/sessions/jwt_helper.rb
module Web
  module Controllers
    module Sessions
      module JwtHelper
        # ...
      end
    end
  end
end
```

```bash
❯ be hanami console
bundler: failed to load command: hanami (/Users/nico/.gem/ruby/2.3.1/bin/hanami)
NameError: uninitialized constant Web::Controllers::Sessions::Create::JwtHelper
  /Users/nico/_dev/Ruby/inventory/apps/web/controllers/sessions/create.rb:9:in `<class:Create>'
  /Users/nico/_dev/Ruby/inventory/apps/web/controllers/sessions/create.rb:6:in `<module:Sessions>'
  /Users/nico/_dev/Ruby/inventory/apps/web/controllers/sessions/create.rb:5:in `<module:Controllers>'
  /Users/nico/_dev/Ruby/inventory/apps/web/controllers/sessions/create.rb:4:in `<module:Web>'
  /Users/nico/_dev/Ruby/inventory/apps/web/controllers/sessions/create.rb:3:in `<top (required)>'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-utils-1.0.0.beta1/lib/hanami/utils.rb:52:in `require_relative'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-utils-1.0.0.beta1/lib/hanami/utils.rb:52:in `block in require!'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-utils-1.0.0.beta1/lib/hanami/utils.rb:90:in `each'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-utils-1.0.0.beta1/lib/hanami/utils.rb:90:in `for_each_file_in'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-utils-1.0.0.beta1/lib/hanami/utils.rb:52:in `require!'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/config/load_paths.rb:17:in `block in load!'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-utils-1.0.0.beta1/lib/hanami/utils/load_paths.rb:65:in `block in each'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-utils-1.0.0.beta1/lib/hanami/utils/load_paths.rb:64:in `each'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-utils-1.0.0.beta1/lib/hanami/utils/load_paths.rb:64:in `each'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/config/load_paths.rb:16:in `load!'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components/components.rb:384:in `block (2 levels) in <module:Components>'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components/component.rb:38:in `call'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components/components.rb:302:in `block (3 levels) in <module:Components>'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components/components.rb:301:in `each'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components/components.rb:301:in `block (2 levels) in <module:Components>'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components/component.rb:38:in `call'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components/components.rb:230:in `block (3 levels) in <module:Components>'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/configuration.rb:45:in `block in apps'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/configuration.rb:44:in `each_pair'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/configuration.rb:44:in `apps'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components/components.rb:229:in `block (2 levels) in <module:Components>'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components/component.rb:42:in `call'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components.rb:85:in `block (2 levels) in resolve'
  /Users/nico/.gem/ruby/2.3.1/gems/concurrent-ruby-1.0.4/lib/concurrent/map.rb:133:in `block in fetch_or_store'
  /Users/nico/.gem/ruby/2.3.1/gems/concurrent-ruby-1.0.4/lib/concurrent/map.rb:122:in `fetch'
  /Users/nico/.gem/ruby/2.3.1/gems/concurrent-ruby-1.0.4/lib/concurrent/map.rb:132:in `fetch_or_store'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components.rb:83:in `block in resolve'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components.rb:82:in `each'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components.rb:82:in `resolve'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components/component.rb:136:in `resolve_requirements'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components/component.rb:34:in `call'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components.rb:85:in `block (2 levels) in resolve'
  /Users/nico/.gem/ruby/2.3.1/gems/concurrent-ruby-1.0.4/lib/concurrent/map.rb:133:in `block in fetch_or_store'
  /Users/nico/.gem/ruby/2.3.1/gems/concurrent-ruby-1.0.4/lib/concurrent/map.rb:122:in `fetch'
  /Users/nico/.gem/ruby/2.3.1/gems/concurrent-ruby-1.0.4/lib/concurrent/map.rb:132:in `fetch_or_store'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components.rb:83:in `block in resolve'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components.rb:82:in `each'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/components.rb:82:in `resolve'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/commands/command.rb:47:in `initialize'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/commands/console.rb:47:in `initialize'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/cli.rb:84:in `new'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/lib/hanami/cli.rb:84:in `console'
  /Users/nico/.gem/ruby/2.3.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /Users/nico/.gem/ruby/2.3.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/nico/.gem/ruby/2.3.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /Users/nico/.gem/ruby/2.3.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /Users/nico/.gem/ruby/2.3.1/gems/hanami-1.0.0.beta1/bin/hanami:5:in `<top (required)>'
  /Users/nico/.gem/ruby/2.3.1/bin/hanami:23:in `load'
  /Users/nico/.gem/ruby/2.3.1/bin/hanami:23:in `<top (required)>'
```

I created a super basic Hanami app to reproduce the issue [here](https://github.com/nickgnd/hanami-autoloading)

Please let me know if I can help, 
Thanks again.

---

related issues an PRs:
- #646  Issue with load_paths
- #655 Add .sort to glob, to fix OS X / Linux discrepancy
- [Introducing Hanami::Utils::FileList](https://github.com/hanami/utils/pull/163)

---

My environment:

```bash
❯ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]                                                                                                                     
❯ hanami -v
v1.0.0.beta1
❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1004
```

**Comment by mereghost** [comment]
@nickgnd Hello and thanks for your kind words and feedback. How did you expect it to behave?

**Comment by mereghost** [comment]
Glad to be of help. The best way to ensure a proper load order is requiring the file where it's needed.

I'll close this then. =)
