### ISSUE TITLE
NoMethodError on nil: hanami/mailer/dsl.rb:84:in `templates'

### ISSUE THREAD

**Issue by alcesleo** [hanami/hanami#751]
When trying to get mailers set up I keep running into this problem - it might be because of a misconfiguration but it is not providing me enough information to understand what is missing.

It can be reproduced by generating a new hanami app, then instantly generating a mailer, setting the 3 fields in the mailer and trying to `deliver` via the console. At this point the mailer is obviously not configured properly yet, but while trying to proceed to configure it I was unable to get past this error.

### Version

```
$ hanami -v
v1.0.0.beta2
```

### Gemfile.lock

https://gist.github.com/alcesleo/d3e19290f70aadd9a46c796acdd51271

### Stacktrace

The error occurs here: https://github.com/hanami/mailer/blob/d0deef38699b89eaab38e1bdeee9610be4840c37/lib/hanami/mailer/dsl.rb#L84

```
irb(main):001:0> Mailers::TestMailer.deliver
NoMethodError: undefined method `fetch' for nil:NilClass
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hanami-mailer-1.0.0.beta1/lib/hanami/mailer/dsl.rb:84:in `templates'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hanami-mailer-1.0.0.beta1/lib/hanami/mailer.rb:324:in `__part?'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hanami-mailer-1.0.0.beta1/lib/hanami/mailer.rb:312:in `__part'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hanami-mailer-1.0.0.beta1/lib/hanami/mailer.rb:289:in `block in build'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hanami-mailer-1.0.0.beta1/lib/hanami/mailer.rb:281:in `tap'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hanami-mailer-1.0.0.beta1/lib/hanami/mailer.rb:281:in `build'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hanami-mailer-1.0.0.beta1/lib/hanami/mailer.rb:201:in `initialize'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hanami-mailer-1.0.0.beta1/lib/hanami/mailer.rb:186:in `new'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hanami-mailer-1.0.0.beta1/lib/hanami/mailer.rb:186:in `deliver'
        from (irb):1
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hanami-1.0.0.beta2/lib/hanami/commands/console.rb:55:in `start'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hanami-1.0.0.beta2/lib/hanami/cli.rb:84:in `console'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
... 2 levels...
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/hanami:23:in `<top (required)>'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
        from /Users/alcesleo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
        from /Users/alcesleo/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
        from /Users/alcesleo/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```

**Comment by mereghost** [comment]
@alcesleo Is it a new project or you were upgrading an old one?

**Comment by alcesleo** [comment]
It is a new project, I reproduced it by generating a completely fresh one without altering config/environment.rb. In the project I first encountered it I have tried to configure some stuff in that file but none of those changes changed this behaviour. If you still think the config/environment.rb is relevant I'll post it as soon as I get the chance!

**Comment by mereghost** [comment]
@alcesleo can you confirm if the same happens when using the test environment? 

```
$> HANAMI_ENV=test bundle exec hanami console
hanami> Mailers::TestMailer.deliver
```

**Comment by mereghost** [comment]
Upon further investigation it seems that this problem is related to our implementation of code reloading. =/

**Comment by alcesleo** [comment]
It seems to work fine in the test environment, but I think you already solved it? :)

**Comment by alcesleo** [comment]
I'm sorry to say that this is still reproducible with hanami 1.0.0.beta3 and hanami-mailer 1.0.0.beta2

**Comment by mereghost** [comment]
Gah! Code reloading is eating us alive. >.<

I'll check it again, but the core of the issue lies around the code reloading and the fact that most magic happens on the `included` hook of `Hanami::Mailer`.

**Comment by alcesleo** [comment]
Thank you! It looks tricky

**Comment by jodosha** [comment]
@alcesleo Can you please try with `master`? Thanks.

**Comment by alcesleo** [comment]
Will give it a shot as soon as I have time! Thank you!

**Comment by alcesleo** [comment]
I can confirm that changing `gem "hanami", "1.0.0.beta3"` to `gem "hanami", github: "hanami/hanami"` does solve this issue. :)

**Comment by jodosha** [comment]
@alcesleo Thanks for getting back. I'm happy this is fixed for you. 😉

**Comment by alcesleo** [comment]
My pleasure, thanks a lot!
