### ISSUE TITLE
`Hanami::Utils.reload!` is used in development regardless if code-reloading is used or not.

### ISSUE THREAD

**Issue by ixti** [hanami/hanami#758]
I found subj while using `Dry::Struct` for one of my entities. Latter one does not plays well when double loaded with `load` leading to `Dry::Struct::RepeatedAttributeError` exception being raised:

```
>>= bundle exec hanami c
bundler: failed to load command: hanami (/home/ixti/.gem/ruby/2.4.0/bin/hanami)
Dry::Struct::RepeatedAttributeError: Attribute :id has already been defined
  /home/ixti/.gem/ruby/2.4.0/gems/dry-struct-0.2.1/lib/dry/struct/class_interface.rb:56:in `check_schema_duplication'
  /home/ixti/.gem/ruby/2.4.0/gems/dry-struct-0.2.1/lib/dry/struct/class_interface.rb:40:in `attributes'
  /home/ixti/.gem/ruby/2.4.0/gems/dry-struct-0.2.1/lib/dry/struct/class_interface.rb:36:in `attribute'
  /home/ixti/playing-with-hanami/example/lib/example/entities/access_token.rb:8:in `<class:AccessToken>'
  /home/ixti/playing-with-hanami/example/lib/example/entities/access_token.rb:3:in `<top (required)>'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-utils-1.0.0.beta3/lib/hanami/utils.rb:68:in `load'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-utils-1.0.0.beta3/lib/hanami/utils.rb:68:in `block in reload!'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-utils-1.0.0.beta3/lib/hanami/utils.rb:90:in `each'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-utils-1.0.0.beta3/lib/hanami/utils.rb:90:in `for_each_file_in'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-utils-1.0.0.beta3/lib/hanami/utils.rb:68:in `reload!'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components/components.rb:59:in `block (2 levels) in <module:Components>'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components/component.rb:40:in `call'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:85:in `block (2 levels) in resolve'
  /home/ixti/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:133:in `block in fetch_or_store'
  /home/ixti/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:122:in `fetch'
  /home/ixti/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:132:in `fetch_or_store'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:83:in `block in resolve'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:82:in `each'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:82:in `resolve'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components/component.rb:138:in `resolve_requirements'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components/component.rb:36:in `call'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:85:in `block (2 levels) in resolve'
  /home/ixti/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:133:in `block in fetch_or_store'
  /home/ixti/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:122:in `fetch'
  /home/ixti/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:132:in `fetch_or_store'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:83:in `block in resolve'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:82:in `each'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:82:in `resolve'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/commands/command.rb:57:in `initialize'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/commands/console.rb:52:in `initialize'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/cli.rb:89:in `new'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/cli.rb:89:in `console'
  /home/ixti/.gem/ruby/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /home/ixti/.gem/ruby/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /home/ixti/.gem/ruby/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /home/ixti/.gem/ruby/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/bin/hanami:5:in `<top (required)>'
  /home/ixti/.gem/ruby/2.4.0/bin/hanami:22:in `load'
  /home/ixti/.gem/ruby/2.4.0/bin/hanami:22:in `<top (required)>'
```

I wasn't able to receive any replies in dry-rb chat if it's possible to disable attributes schema checks. Although from my investigation of dry-struct code it's impossible. I believe that hanami should provide a way to explicitly disable code reloading everywhere (thus `require` will be used all the time, not `load`) not only for server but for console and everything else as well.

**Comment by davydovanton** [comment]
hey, could you paste code from `/home/ixti/playing-with-hanami/example/lib/example/entities/access_token.rb` file? :)

**Comment by ixti** [comment]
Sure:

``` ruby
class AccessToken < Dry::Struct
  attribute :id,     Types::String.default { SecureRandom.uuid }
  attribute :secret, Types::String
  attribute :digest, Types::String
end
```

In fact I just pushed a fresh-new demo of this issue:
https://github.com/ixti/hanami-reload-issue/

**Comment by davydovanton** [comment]
hm, I think the problem in default value for id type `Types::String.default { SecureRandom.uuid }`. 
I know that it's a hack but you can define default value in constructor (`#initialize`)

@hanami/core any ideas?

**Comment by ixti** [comment]
unfortunately [no, it's not](https://github.com/ixti/hanami-reload-issue/commit/0d621b0baee6fa308c0786c07db0127a1784c1f3). If you will remove `:id` attribute line it will start complaining about next one:

```
bundler: failed to load command: hanami (/home/ixti/.gem/ruby/2.4.1/bin/hanami)
Dry::Struct::RepeatedAttributeError: Attribute :secret has already been defined
  /home/ixti/.gem/ruby/2.4.1/gems/dry-struct-0.2.1/lib/dry/struct/class_interface.rb:56:in `check_schema_duplication'
  /home/ixti/.gem/ruby/2.4.1/gems/dry-struct-0.2.1/lib/dry/struct/class_interface.rb:40:in `attributes'
  /home/ixti/.gem/ruby/2.4.1/gems/dry-struct-0.2.1/lib/dry/struct/class_interface.rb:36:in `attribute'
  /home/ixti/hanami-reload-issue/lib/playing_with_hanami/entities/access_token.rb:7:in `<class:AccessToken>'
  /home/ixti/hanami-reload-issue/lib/playing_with_hanami/entities/access_token.rb:6:in `<top (required)>'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-utils-1.0.0.beta3/lib/hanami/utils.rb:68:in `load'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-utils-1.0.0.beta3/lib/hanami/utils.rb:68:in `block in reload!'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-utils-1.0.0.beta3/lib/hanami/utils.rb:90:in `each'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-utils-1.0.0.beta3/lib/hanami/utils.rb:90:in `for_each_file_in'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-utils-1.0.0.beta3/lib/hanami/utils.rb:68:in `reload!'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-1.0.0.beta3/lib/hanami/components/components.rb:59:in `block (2 levels) in <module:Components>'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-1.0.0.beta3/lib/hanami/components/component.rb:40:in `call'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:85:in `block (2 levels) in resolve'
  /home/ixti/.gem/ruby/2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:133:in `block in fetch_or_store'
  /home/ixti/.gem/ruby/2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:122:in `fetch'
  /home/ixti/.gem/ruby/2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:132:in `fetch_or_store'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:83:in `block in resolve'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:82:in `each'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:82:in `resolve'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-1.0.0.beta3/lib/hanami/components/component.rb:138:in `resolve_requirements'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-1.0.0.beta3/lib/hanami/components/component.rb:36:in `call'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:85:in `block (2 levels) in resolve'
  /home/ixti/.gem/ruby/2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:133:in `block in fetch_or_store'
  /home/ixti/.gem/ruby/2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:122:in `fetch'
  /home/ixti/.gem/ruby/2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:132:in `fetch_or_store'
  1 [core]                                                                           
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:83:in `block in resolve'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:82:in `each'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:82:in `resolve'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-1.0.0.beta3/lib/hanami/commands/command.rb:57:in `initialize'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-1.0.0.beta3/lib/hanami/commands/console.rb:52:in `initialize'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-1.0.0.beta3/lib/hanami/cli.rb:89:in `new'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-1.0.0.beta3/lib/hanami/cli.rb:89:in `console'
  /home/ixti/.gem/ruby/2.4.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  1 [core]                                                                           
  /home/ixti/.gem/ruby/2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /home/ixti/.gem/ruby/2.4.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /home/ixti/.gem/ruby/2.4.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /home/ixti/.gem/ruby/2.4.1/gems/hanami-1.0.0.beta3/bin/hanami:5:in `<top (required)>'
  /home/ixti/.gem/ruby/2.4.1/bin/hanami:22:in `load'
  /home/ixti/.gem/ruby/2.4.1/bin/hanami:22:in `<top (required)>'
```

**Comment by ixti** [comment]
Let's start with root of this problem: dry-struct. It does not allows redefining (even with same options) fields. Let's start with simple code:

``` ruby
require "dry-types"
require "dry-struct"

module Types
  include Dry::Types.module
end

class AccessToken < Dry::Struct
  attribute :secret, Types::String
end
```

We can easily re-open this class and add new attributes:

``` ruby
class AccessToken < Dry::Struct
  attribute :digest, Types::String
end
```

So now `AccessToken` will have 2 attributes: `:secrect` and `:digest`. But if you will try to re-define `:secret` attribute even with same (let's call it) signature, you will get that error. Just repeat initial AccessToken code:

```
[8] pry(main)> class AccessToken < Dry::Struct
[8] pry(main)*   attribute :secret, Types::String  
[8] pry(main)* end  
Dry::Struct::RepeatedAttributeError: Attribute :secret has already been defined
from /home/ixti/.gem/ruby/2.4.1/gems/dry-struct-0.2.1/lib/dry/struct/class_interface.rb:56:in `check_schema_duplication'
```

BOOM!

To be continued... :D

**Comment by ixti** [comment]
Now let's take a look on the issue from hanami perspective. Issue is happening due to the way hot code reloading works. Here's default generated [entry point](https://github.com/ixti/hanami-reload-issue/blob/master/lib/playing_with_hanami.rb) of a project:

``` ruby
Hanami::Utils.require!("#{__dir__}/playing_with_hanami")
```

That is absolutely fine in fact. Her'es what we have in [utils](https://github.com/hanami/utils/blob/4e5358245d82515f8f4a3023db1f8a97718f2a86/lib/hanami/utils.rb#L51-L69):

``` ruby
    def self.require!(directory)
      for_each_file_in(directory) { |file| require_relative(file) }
    end

    def self.reload!(directory)
      for_each_file_in(directory) { |file| load(file) }
    end
```

Very important part here is `reload!` method. It's very important because [following block](https://github.com/ixti/hanami/blob/78840d4acacc82c828b5f6933546df10aacbc2ac/lib/hanami/components/components.rb#L54-L64):

``` ruby
    register 'code' do
      run do
        directory = Hanami.root.join('lib')

        if Components['environment'].code_reloading?
          Utils.reload!(directory)
        else
          Utils.require!(directory)
        end
      end
    end
```

Notice `Components['environment'].code_reloading?` because that will be `true` ALL the time (regardless of anything) in `development` [environment](https://github.com/ixti/hanami/blob/78840d4acacc82c828b5f6933546df10aacbc2ac/lib/hanami/environment.rb#L429-L431):

``` ruby
    def code_reloading?
      @options.fetch(:code_reloading) { !!CODE_RELOADING[environment] }
    end
```

**Comment by jodosha** [comment]
@ixti I'm sorry about this problem and thank you for the in depth analysis.

---

As now, Hanami loads twice the code under `lib/`. This is inefficient, but "fine" in case:

  * A dev uses `hanami-model`
  * A dev disables code reloading (via `hanami server --no-code-reloading`)

When other libs are used, this boot system can blow up, like in this case with `dry-struct`.

---

In order to simplify the framework internals, I'm trying to make Hanami less configurable in a few spots. For instance, we always want model domain to be defined in `lib/`. For this reason, I introduced that `"code"` component that hard-code this concept, and in fact it forces it.

As a side note, it's worth to mention that this was choice was forced by the code reloading issues that we had in the past (eg. the `0.8.x` series).

---

If we remove the following line from `lib/playing_with_hanami.rb`, the @ixti demo project works.

```ruby
Hanami::Utils.require!("#{__dir__}/playing_with_hanami")
```

---

I suggest to fix this, by generating an empty `lib/<project_name>.rb` file. This also avoids the double code require problem.

@hanami/core thoughts?

**Comment by ixti** [comment]
I found when even with #762 hanami console will fail. If some file will have `require` of that entity:

``` ruby
# file: lib/example/operations/create_token.rb

require_relative "../entities/access_token"
require_relative "../repositories/access_token_repository"

class CreateToken < Operation
  # ...
end
```

More than that. If any of files will have module/class with some constants defined, and that file will be required, a warning will be shown, e.g.:

```
warning: already initialized constant MessageEncryptor::Signature
```

**Comment by ixti** [comment]
@jodosha I can update demo repo with what I mean to prove that it's a valid use case that fails due to usage of `load` :D

**Comment by ixti** [comment]
To keep it simple, problem comes when one wants to "control" what is required when. One good reason for that is, e.g. I need to `require "../types"` in my dry-struct based entities, otherwise code load will fail as types are loaded after entities.

**Comment by jodosha** [comment]
Please update, as I want to fix this ASAP. Thanks.

http://lucaguidi.com

**Comment by ixti** [comment]
@jodosha Okay I pushed two commits to show the problem from 2 different angles.

[First one](https://github.com/ixti/hanami-reload-issue/commit/fa0921cf5362fb5d99930781a12e6c0c74b809a8) is pretty "opinionated". Personally I prefer to explicitly specify all my dependencies either with `require` (or `require_relative`) or with `autoload :Bar, "foo/bar"` (it won't work with hanami though - because we don't add `lib` into `$LOAD_PATH` which is something I wanted to discuss separately).

[Second](https://github.com/ixti/hanami-reload-issue/commit/e5cea90c046f4af212ee374bf69f6437e6d803c5) shows a case where `require` is actually needed. It happens due to by default files are loaded in alphabetical order and if `A` needs `B` we got this problem.

Of course one may say that I should use DI, and, for example, using block form of Dry::Schema, but that's like trying to solve problem by closing eyes on it. So I have added [third](https://github.com/ixti/hanami-reload-issue/commit/7911f75bb4e1b02de608610757bba4d1f146b110) patch that will cause ruby to show warnings:

```
.../lib/playing_with_hanami/services/base.rb:3: warning: already initialized constant Services::Base::SOME_CONST
.../lib/playing_with_hanami/services/base.rb:3: warning: previous definition of SOME_CONST was here
```

**Comment by ixti** [comment]
Small clarification on how to "see" problems in action:

```
git fetch

# example 1:
git reset --hard origin/master 
rm -rf lib/playing_with_hanami/actors,services}
bundle exec hanami c

# exmple 2:
git reset --hard origin/master 
rm -rf lib/playing_with_hanami/{operations,services}
bundle exec hanami c

# exmple 3:
git reset --hard origin/master 
rm -rf lib/playing_with_hanami/{actors,operations}
bundle exec hanami c
```

**Comment by aebejer** [comment]
@ixti did you end up finding a good way to solve this problem? thanks!

**Comment by ixti** [comment]
@aebejer mm.. I don't remember. The project I was using Hanami for did not succeeded due to management issues.
