### ISSUE TITLE
Issue with Hanami::Utils.reload!

### ISSUE THREAD

**Issue by vladra** [hanami/hanami#775]
Hi guys!

I'm using hanami 0.9, and finally got a chance to upgrade it to 1.0

It's related to #758 , but I don't see how that solution can solve my problem. I don't have that file at all (tried to add empty one though). 

So, basically problem itself is exactly the same. In production I can start server successfully. But in development I can't start console, or can't start server because of file being loaded second time.

In my case it breaks because of `statesman` gem calling same class method twice (via dsl). If it will pass, I'm pretty sure it will fail on the `dry-struct` next.

Is there any way to force disable code reloading in development? I seems that this line always returns true: `Components['environment'].code_reloading?`

Hanami related backtrace is:
```
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-utils-1.0.0/lib/hanami/utils.rb:68:in `load'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-utils-1.0.0/lib/hanami/utils.rb:68:in `block in reload!'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-utils-1.0.0/lib/hanami/utils.rb:90:in `each'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-utils-1.0.0/lib/hanami/utils.rb:90:in `for_each_file_in'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-utils-1.0.0/lib/hanami/utils.rb:68:in `reload!'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/components/components.rb:59:in `block (2 levels) in <module:Components>'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/components/component.rb:40:in `call'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/components.rb:85:in `block (2 levels) in resolve'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:133:in `block in fetch_or_store'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:122:in `fetch'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:132:in `fetch_or_store'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/components.rb:83:in `block in resolve'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/components.rb:82:in `each'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/components.rb:82:in `resolve'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/components/component.rb:138:in `resolve_requirements'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/components/component.rb:36:in `call'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/components.rb:85:in `block (2 levels) in resolve'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:133:in `block in fetch_or_store'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:122:in `fetch'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:132:in `fetch_or_store'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/components.rb:83:in `block in resolve'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/components.rb:82:in `each'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/components.rb:82:in `resolve'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/commands/command.rb:57:in `initialize'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/commands/console.rb:52:in `initialize'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/cli.rb:89:in `new'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/cli.rb:89:in `console'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/bin/hanami:5:in `<top (required)>'
  /usr/local/opt/rbenv/versions/2.3.3/bin/hanami:22:in `load'
  /usr/local/opt/rbenv/versions/2.3.3/bin/hanami:22:in `<top (required)>'
```

**Comment by vladra** [comment]
Just found how to solve it from test examples, but maybe there is better suited approach to solve my problem, other then using internal api.

**Comment by davydovanton** [comment]
@vladra sorry for the long response.

@hanami/core could you check this? thanks!

**Comment by nessur** [comment]
adding `code_reloading` to the cli.rb seems like an easy fix, since the feature doesnt _realy_ make sense for console mode:
```
    method_option :environment, desc: 'Path to environment configuration (config/environment.rb)'
    method_option :engine, desc: "Choose a specific console engine: (#{Hanami::Commands::Console::ENGINES.keys.join('/')})"
    method_option :help, desc: 'Displays the usage method'
    method_option :code_reloading, desc: 'Code reloading', type: :boolean, default: false
    # @api private
    def console
      if options[:help]
        invoke :help, ['console']
      else
        Hanami::Commands::Console.new(options).start
      end
    end
```

**Comment by jodosha** [comment]
Folks, IMO `Hanami::Utils.reload!` is and it will be a source of troubles both for people using Hanami and for us as maintainers.

Would you please give this gem a try? https://github.com/jodosha/hanami-reloader
It replaces `Hanami::Utils.reload!` behavior, and uses `guard`, instead of `shotgun` for code reloading. I tried to work with this gem for more than a month and it's a decent first release.

Please let me know.
