### ISSUE TITLE
Non-hanami folder in /apps dir

### ISSUE THREAD

**Issue by mbajur** [hanami/hanami#790]
Hello!

I'm trying to create a SPA + hanami backend website and decided it would be pretty good idea to put my frontend code (written in node/js/vue.js) in `/apps/frontend`.

The problem is - when i'm trying to run a generator command (`$ hanami g action web application#index`), hanami throws:

```
/Users/mbajur/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/environment.rb:404:in `require': cannot load such file -- /Volumes/SUPPORT/Workspace/Personal/my_app/xxx/apps/frontend/config/environment (LoadError)
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/environment.rb:404:in `require_application_environment'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/commands/command.rb:53:in `initialize'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/commands/generate/abstract.rb:25:in `initialize'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/commands/generate/action.rb:66:in `initialize'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/cli_sub_commands/generate.rb:50:in `new'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/cli_sub_commands/generate.rb:50:in `actions'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor.rb:242:in `block in subcommand'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/bin/hanami:5:in `<top (required)>'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/bin/hanami:22:in `load'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/bin/hanami:22:in `<main>'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/mbajur/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

This makes me think that hanami expects any folder in `/apps` to be a hanami sub-application. Which is totally reasonable. But what if it's not? Is there any way to tell hanami that i'm not keeping hanami-related code in there?

Thanks in advance

**Comment by b264** [comment]
I would definitely put the frontend behind the [fingerprint mode](http://hanamirb.org/guides/assets/overview/) to avoid cache issues

**Comment by TiteiKo** [comment]
I don't think hanami expects this.. The error message makes me think that there is an actual problem in your code. It looks like you somewhere have a requirement for `/apps/frontend/config/environment` (a file that is not part of the hanami app structure)

I've tried reproducing the problem but couldn't:

```
hanami new node
cd node
bundle install
mkdir apps/frontend
touch apps/frontend/index.js
bundle exec hanami g action web application#index
```

The generation command just does its job:
```                                                                                                                                                                                                                                                                     
└─< (master)* >──» bundle exec hanami g action web application#index                                                                                                                                                                                                                                              0 < 08:37:19
      create  spec/web/controllers/application/index_spec.rb
      create  apps/web/controllers/application/index.rb
      create  apps/web/views/application/index.rb
      create  apps/web/templates/application/index.html.erb
      create  spec/web/views/application/index_spec.rb
      insert  apps/web/config/routes.rb
```

Could you be more specific on what you did and what you want to achieve?

**Comment by mbajur** [comment]
I checked everything twice and... i'm an idiot, i was trying to run `hanami c` from inside the `apps/frontend` directory instead of the root dir. I'm very sorry for confusion and fatigue.

**Comment by TiteiKo** [comment]
No worries, I'm glad you found the answer to your problem :)
