### ISSUE TITLE
dotenv gem not installed as a dependency

### ISSUE THREAD

**Issue by mwlang** [hanami/hanami#807]
While trying to follow along on the tutorial in Getting Started, encountered this error at the point of creating the new hanami project:

~~~bash
08:56:20:hanami >> hanami new bookshelf --database=postgresql
      create  .hanamirc
      create  .env.development
      create  .env.test
      create  Gemfile
      create  config.ru
      create  config/boot.rb
      create  config/environment.rb
      create  lib/bookshelf.rb
      create  public/.gitkeep
      create  config/initializers/.gitkeep
      create  lib/bookshelf/entities/.gitkeep
      create  lib/bookshelf/repositories/.gitkeep
      create  lib/bookshelf/mailers/.gitkeep
      create  lib/bookshelf/mailers/templates/.gitkeep
      create  spec/bookshelf/entities/.gitkeep
      create  spec/bookshelf/repositories/.gitkeep
      create  spec/bookshelf/mailers/.gitkeep
      create  spec/support/.gitkeep
      create  db/migrations/.gitkeep
      create  Rakefile
      create  spec/spec_helper.rb
      create  spec/features_helper.rb
      create  db/schema.sql
      create  .gitignore
         run  git init . from "."
/Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/env.rb:59:in `load!': uninitialized constant Dotenv::Parser (NameError)
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/environment.rb:522:in `set_application_env_vars!'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/environment.rb:504:in `set_env_vars!'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/environment.rb:207:in `block in initialize'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/environment.rb:207:in `synchronize'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/environment.rb:207:in `initialize'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/commands/generate/app.rb:19:in `new'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/commands/generate/app.rb:19:in `initialize'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/commands/new/container.rb:97:in `new'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/commands/new/container.rb:97:in `generate_app'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/commands/new/container.rb:43:in `post_process_templates'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/generators/generatable.rb:39:in `process_templates'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/generators/generatable.rb:12:in `start'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/commands/new/abstract.rb:61:in `block in start'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/commands/new/abstract.rb:58:in `chdir'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/commands/new/abstract.rb:58:in `start'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/lib/hanami/cli.rb:122:in `new'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/gems/hanami-1.0.0/bin/hanami:5:in `<top (required)>'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/bin/hanami:22:in `load'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/bin/hanami:22:in `<main>'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/mwlang/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
~~~

Turns out I did not have dotenv gem installed.  After fixing with:

~~~
gem install dotenv
~~~

Creating the project works:

~~~bash
09:00:35:hanami >> hanami new bookshelf --database=postgresql
   identical  .hanamirc
   identical  .env.development
   identical  .env.test
   identical  Gemfile
   identical  config.ru
   identical  config/boot.rb
   identical  config/environment.rb
   identical  lib/bookshelf.rb
   identical  public/.gitkeep
   identical  config/initializers/.gitkeep
   identical  lib/bookshelf/entities/.gitkeep
   identical  lib/bookshelf/repositories/.gitkeep
   identical  lib/bookshelf/mailers/.gitkeep
   identical  lib/bookshelf/mailers/templates/.gitkeep
   identical  spec/bookshelf/entities/.gitkeep
   identical  spec/bookshelf/repositories/.gitkeep
   identical  spec/bookshelf/mailers/.gitkeep
   identical  spec/support/.gitkeep
   identical  db/migrations/.gitkeep
   identical  Rakefile
   identical  spec/spec_helper.rb
   identical  spec/features_helper.rb
   identical  db/schema.sql
      create  apps/web/application.rb
      create  apps/web/config/routes.rb
      create  apps/web/views/application_layout.rb
      create  apps/web/templates/application.html.erb
      create  apps/web/assets/favicon.ico
      create  apps/web/controllers/.gitkeep
      create  apps/web/assets/images/.gitkeep
      create  apps/web/assets/javascripts/.gitkeep
      create  apps/web/assets/stylesheets/.gitkeep
      create  spec/web/features/.gitkeep
      create  spec/web/controllers/.gitkeep
      create  spec/web/views/.gitkeep
      insert  config/environment.rb
      insert  config/environment.rb
      append  .env.development
      append  .env.test
~~~

**Comment by jodosha** [comment]
@mwlang Thanks for reporting this. I'm working on the CLI, so I'll fix this too.
Enjoy Hanami! 🌸

**Comment by cllns** [comment]
@jodosha Can you let me know what this error is? I looked it and it looks like we have a guard clause to catch exactly this:
https://github.com/hanami/hanami/blob/master/lib/hanami/env.rb#L56-L59 

```
return unless defined?(Dotenv)

contents = ::File.open(path, "rb:bom|utf-8", &:read)
parsed = Dotenv::Parser.call(contents)
```
I can't reproduce it, even on a ruby without dotenv installed.

So, the question is, how is `Dotenv` defined but not `Dotenv::Parser`, especially since `require 'dotenv'` [loads the parser as its very first line](https://github.com/bkeepers/dotenv/blob/master/lib/dotenv.rb#L1). `dotenv-rails` should load the parser too.

**Comment by jodosha** [comment]
@cllns Shall we make things more explicit?

  1. Add a `require "dotenv/parser"`
  2. `return unless defined?(Dotenv::Parser)`

**Comment by cllns** [comment]
@jodosha I still don't see how the current solution failed, so I'm not sure if that'll fix it. Line 56 of `lib/hanami/env.rb`is `return unless defined?(Dotenv)` and somehow it got past that, without the `dotenv` gem being installed?

**Comment by cllns** [comment]
I just tried to reproduce this with ruby 2.4.1, without `dotenv` installed and I couldn't :/

**Comment by jodosha** [comment]
@mwlang Did you created the new project from Hanami git repository?

I mean, did you ran the following commands?

```shell
git clone https://github.com/hanami/hanami.git
cd hanami
hanami new bookshelf --database=postgresql
```

I'm asking because your prompt reports `hanami` on the left:

```shell
08:56:20:hanami >> ...
```

**Comment by mwlang** [comment]
@jbodah no.  gem installed hanami.  However, it occurred to me to take a look at my gem environment, and I suspect I now know what happened:

11:13:22:bookshelf >> gem list dotenv
*** LOCAL GEMS ***
dotenv (2.2.1, 0.10.0)

As you can see, I apparently already had 0.10.0 version of dotenv installed, so this was likely enough to get past  the defined?(Dotenv) guard, but not actually work with Hanami's expectations.

dotenv's not a gem I used directly before, so I didn't even realize it was on my system at all.  I simply did a gem install dotenv w/o looking at the time.

**Comment by cllns** [comment]
@mwlang Thanks! I was able to reproduce this error with `dotenv` `0.10.0`. Will open a PR with a fix now :)
