### ISSUE TITLE
No way whitelist MIME list for whole application

### ISSUE THREAD

**Issue by graywolf** [hanami/hanami#886]
There is a way to whitelist MIME list per action using `accept :html`, but there is no way to whitelist whole application, I personally would like to see `accept :html` in `Hanami::Application` configure block.

Why is this important: Internet Explorer 11 in compatibility mode causes 500 on the server with error

```
Jan 11 11:35:40 saito bash[13494]: #<Hanami::View::MissingTemplateError: Can't find template 'home/index' for 'jpg' format.>
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/hanami-view-1.0.1/lib/hanami/view/rendering.rb:165:in `template'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/hanami-view-1.0.1/lib/hanami/view/rendering.rb:139:in `rendered'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/hanami-view-1.0.1/lib/hanami/view/rendering.rb:153:in `layout'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/hanami-view-1.0.1/lib/hanami/view/rendering.rb:107:in `render'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/hanami-view-1.0.1/lib/hanami/view/rendering.rb:258:in `render'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/hanami-1.0.0/lib/hanami/rendering_policy.rb:56:in `_render_action'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/hanami-1.0.0/lib/hanami/rendering_policy.rb:48:in `_render'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/hanami-1.0.0/lib/hanami/rendering_policy.rb:38:in `render'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/hanami-1.0.0/lib/hanami/application.rb:169:in `call'
Jan 11 11:35:40 saito bash[13494]: /usr/lib/ruby/2.5.0/delegate.rb:83:in `method_missing'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/http_router-0.11.2/lib/http_router.rb:193:in `process_destination_path'
Jan 11 11:35:40 saito bash[13494]: (eval):38:in `call'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/http_router-0.11.2/lib/http_router.rb:288:in `raw_call'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/hanami-router-1.0.1/lib/hanami/routing/http_router.rb:156:in `raw_call'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/http_router-0.11.2/lib/http_router.rb:142:in `call'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/hanami-router-1.0.1/lib/hanami/router.rb:1019:in `call'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/rack-2.0.3/lib/rack/content_length.rb:15:in `call'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/rack-2.0.3/lib/rack/builder.rb:153:in `call'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/hanami-1.0.0/lib/hanami/app.rb:42:in `call'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
Jan 11 11:35:40 saito bash[13494]: /home/wolf/srv/postal/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

due to weird accepts list IE11 sends. I solved it by `accept :html` in every
action, but it would be nice to be able to do it in one place (application
configure block).

**Comment by AlfonsoUceda** [comment]
@graywolf can you try this inside you `application.rb`?

```
class Application < Hanami::Application
  configure do
    controller.restrict_mime_types!(['text/html'])
  end
end
```

This method is public in the controller configuration but it is marked as private.

**Comment by graywolf** [comment]
Should probably work, will try on Monday. Should probably not be private then, seems useful.

**Comment by mereghost** [comment]
Heya @graywolf did the workaround proposed by Alfonso help you?

**Comment by jodosha** [comment]
@graywolf Please don't use `restrict_mime_types!` solution as it relies on a **private** API that is subject to change. /cc @AlfonsoUceda

**Comment by graywolf** [comment]
@jodosha clever, thank you :)
