### ISSUE TITLE
Unable to indent Ruby code in erb template

### ISSUE THREAD

**Issue by Pistos** [hanami/hanami#909]
## Steps to Reproduce

```
hanami new erb-bug
cd erb_bug
bundle exec hanami generate action web 'example#index'
${EDITOR} apps/web/templates/example/index.html.erb   # see below for contents of file
bundle exec hanami server
# visit app `/example` path in browser; observe lack of error
${EDITOR} apps/web/templates/example/index.html.erb   # add indentation to <% %> erb code
bundle exec hanami server
```

`index.html.erb`:
```erb
true is...
<% case true %>
<% when true %>
  true.
<% else %>
  false! (wait, what?)
<% end %>
```

Indented might look something like this:

```erb
true is...
  <% case true %>
  <% when true %>
    true.
  <% else %>
    false! (wait, what?)
  <% end %>
```

## Actual Behaviour

> Boot Error

> Something went wrong while loading /home/pistos/tmp/erb_bug/config.ru

> SyntaxError: /home/pistos/tmp/erb_bug/apps/web/templates/example/index.html.erb:2: syntax error, unexpected tIDENTIFIER, expecting keyword_when ...<<(-" "); case true ; _erbout.<<(-"\n" ... ^~~~~~~ /home/pistos/tmp/erb_bug/apps/web/templates/example/index.html.erb:3: syntax error, unexpected keyword_when, expecting keyword_end ); _erbout.<<(-" "); when true ; _erbout.<<(-"\n" ^~~~ /home/pistos/tmp/erb_bug/apps/web/templates/example/index.html.erb:14: syntax error, unexpected keyword_end, expecting end-of-input end;end;end;end ^~~

## Expected Behaviour

We are able to indent valid `<% ... %>` expressions without errors.

**Comment by kaikuchn** [comment]
Is this maybe a problem with [tilt](https://github.com/rtomayko/tilt)?

**Comment by kaikuchn** [comment]
In fact it is...
```
❯ cat foo.html.erb
true is...
<% case true %>
<% when true %>
  true.
<% else %>
  false! (wait, what?)
<% end %>

❯ ruby -rtilt -rerb -e "puts Tilt.new('foo.html.erb').render"
true is...
  true.

❯ cat bar.html.erb
true is...
  <% case true %>
  <% when true %>
    true.
  <% else %>
    false! (wait, what?)
  <% end %>

❯ ruby -rtilt -rerb -e "puts Tilt.new('bar.html.erb').render"
bar.html.erb:7: warning: else without rescue is useless
/Users/kaikuchn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:274:in `class_eval': bar.html.erb:2: syntax error, unexpected tIDENTIFIER, expecting keyword_when (SyntaxError)
cat "  ";  case true ; _erbout.concat "\n"
                              ^
bar.html.erb:3: syntax error, unexpected keyword_when, expecting keyword_end
; _erbout.concat "  ";  when true ; _erbout.concat "\n"
                            ^
bar.html.erb:9: syntax error, unexpected keyword_ensure, expecting keyword_end
        ensure
              ^
bar.html.erb:13: syntax error, unexpected keyword_end, expecting end-of-input
end;end;end;end
           ^
	from /Users/kaikuchn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:274:in `compile_template_method'
	from /Users/kaikuchn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:236:in `block in compiled_method'
	from /Users/kaikuchn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:235:in `synchronize'
	from /Users/kaikuchn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:235:in `compiled_method'
	from /Users/kaikuchn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:169:in `evaluate'
	from /Users/kaikuchn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
	from -e:1:in `<main>'
```

**Comment by kaikuchn** [comment]
I guess we should've also made the next logical step and check whether or not this snippet works with plain ERB. Turns out it does not:

```
ruby -rerb -e "puts ERB.new(File.read('bar.html.erb')).result"
/Users/kaikuchn/.rbenv/versions/2.4.2/lib/ruby/2.4.0/erb.rb:896:in `eval': (erb):2: syntax error, unexpected tIDENTIFIER, expecting keyword_when (SyntaxError)
;  case true ; _erbout.concat "\n  "
                      ^
(erb):3: syntax error, unexpected keyword_when, expecting end-of-input
;  when true ; _erbout.concat "\n
       ^
	from /Users/kaikuchn/.rbenv/versions/2.4.2/lib/ruby/2.4.0/erb.rb:896:in `result'
	from -e:1:in `<main>'
```

---> This seems to be invalid ERB?

**Comment by Pistos** [comment]
It seems we can work around it like this:

```
true is...
  <%
  case true
  when true
  %>
    true.
  <% else %>
    false! (wait, what?)
  <% end %>
```
