### ISSUE TITLE
NoMethodError: undefined method `dup' for #<Hanami::Interactor::Result

### ISSUE THREAD

**Issue by 256hax** [hanami/hanami#912]
I got "NoMethodError: undefined method `dup' for #<Hanami::Interactor::Result" when update gem "hanami-view 1.1.0" to "hanami-view 1.1.1".
Is this bug or wrong my code?

# Source Code (Error)
Here is point of code. I copied and customize [hanami /bookshelf](https://github.com/hanami/bookshelf).

### [ Hanami-Bookshelf/apps/web/controllers/books/index.rb ](https://github.com/256hax/Hanami-Bookshelf/blob/master/apps/web/controllers/books/index.rb)
```
...
    expose :books

    def call(params)
      #@books = BookRepository.new.all
      @books = Books::IndexBooks.new.call # call interactor
    end
...
```

### [ Hanami-Bookshelf/lib/bookshelf/interactors/index_books.rb ](https://github.com/256hax/Hanami-Bookshelf/blob/master/lib/bookshelf/interactors/index_books.rb)
```
...
    def initialize(repository: BookRepository.new)
      @repository = repository
    end

    def call
      @list = @repository.all
    end
...
```

### [ Hanami-Bookshelf/apps/web/templates/books/index.html.erb ](https://github.com/256hax/Hanami-Bookshelf/blob/master/apps/web/templates/books/index.html.erb)
```
...
    <% books.list.each do |book| %>
      <div class="book">
        <h2><%= book.title %></h2>
        <p><%= book.author %></p>
      </div>
    <% end %>
...
```

### [ Hanami-Bookshelf/Gemfile ](https://github.com/256hax/Hanami-Bookshelf/blob/master/Gemfile),  [ Hanami-Bookshelf/Gemfile.lock ](https://github.com/256hax/Hanami-Bookshelf/blob/master/Gemfile.lock)
```
...
gem 'rake'
gem 'hanami',       '~> 1.1'
gem 'hanami-model', '~> 1.1'
#gem 'hanami-view',       '1.1.0'

gem 'sqlite3'
...
```

### [All of source code here](https://github.com/256hax/Hanami-Bookshelf)

# Error Message
When I access view (http://localhost:2300/books), I got below error.
```
Boot Error

Something went wrong while loading /Users/*****/Ruby/MyProject/bookshelf/config.ru

NoMethodError: undefined method `dup' for #<Hanami::Interactor::Result:0x007fe998540b08>

/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-utils-1.1.1/lib/hanami/interactor.rb:123:in `block in method_missing'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-utils-1.1.1/lib/hanami/interactor.rb:123:in `fetch'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-utils-1.1.1/lib/hanami/interactor.rb:123:in `method_missing'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-utils-1.1.1/lib/hanami/utils/duplicable.rb:75:in `dup'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-utils-1.1.1/lib/hanami/utils/hash.rb:167:in `block in deep_dup'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-utils-1.1.1/lib/hanami/utils/hash.rb:162:in `each'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-utils-1.1.1/lib/hanami/utils/hash.rb:162:in `each_with_object'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-utils-1.1.1/lib/hanami/utils/hash.rb:162:in `deep_dup'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-view-1.1.1/lib/hanami/view/rendering/layout_scope.rb:129:in `locals'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-view-1.1.1/lib/hanami/view/rendering/scope.rb:48:in `format'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-view-1.1.1/lib/hanami/view/rendering/layout_scope.rb:111:in `format'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-view-1.1.1/lib/hanami/layout.rb:169:in `template'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-view-1.1.1/lib/hanami/layout.rb:139:in `render'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-view-1.1.1/lib/hanami/view/rendering.rb:108:in `render'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-view-1.1.1/lib/hanami/view/rendering.rb:259:in `render'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-1.1.1/lib/hanami/rendering_policy.rb:56:in `_render_action'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-1.1.1/lib/hanami/rendering_policy.rb:48:in `_render'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-1.1.1/lib/hanami/rendering_policy.rb:38:in `render'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-1.1.1/lib/hanami/application.rb:169:in `call'
/Users/*****/.rbenv/versions/2.4.1/lib/ruby/2.4.0/delegate.rb:83:in `method_missing'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/http_router-0.11.2/lib/http_router.rb:193:in `process_destination_path'
(eval):15:in `call'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/http_router-0.11.2/lib/http_router.rb:288:in `raw_call'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-router-1.1.1/lib/hanami/routing/http_router.rb:156:in `raw_call'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/http_router-0.11.2/lib/http_router.rb:142:in `call'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-router-1.1.1/lib/hanami/router.rb:1019:in `call'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/rack-2.0.4/lib/rack/method_override.rb:22:in `call'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-1.1.1/lib/hanami/assets/static.rb:49:in `call'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/rack-2.0.4/lib/rack/content_length.rb:15:in `call'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/rack-2.0.4/lib/rack/common_logger.rb:33:in `call'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/rack-2.0.4/lib/rack/builder.rb:153:in `call'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-1.1.1/lib/hanami/app.rb:42:in `call'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:86:in `proceed_as_child'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:31:in `call!'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:18:in `call'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/hanami-1.1.1/lib/hanami/assets/static.rb:49:in `call'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/rack-2.0.4/lib/rack/lint.rb:49:in `_call'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/rack-2.0.4/lib/rack/lint.rb:37:in `call'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/rack-2.0.4/lib/rack/show_exceptions.rb:23:in `call'
/Users/*****/Ruby/MyProject/bookshelf/vendor/bundler/ruby/2.4.0/gems/rack-2.0.4/lib/rack/handler/webrick.rb:86:in `service'
/Users/*****/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
/Users/*****/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
/Users/*****/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
```

# Expected behavior
I expected display books data. It works fine if use "hanami-view 1.1.0" gem.
<img width="331" alt="2018-03-09 23 55 24" src="https://user-images.githubusercontent.com/1146563/37213556-c0d5b420-23f5-11e8-9bf0-3c612b0ab361.png">

# I tried this but still error
- bundle update "hanami 1.1.0 to 1.1.1" and "hanami 1.1.0 to 1.2.0.beta1".
- bundle update "hanami-utils 1.1.2 to 1.1.1".

**Comment by cllns** [comment]
`Hanami::Interactor::Result` doesn't inherit from `::Object`, which is why `#dup` cannot be found.

`Hanami::Interactor::Result`, itself, isn't designed to be rendered in a template. I think what you want is to expose `list` from the Interactor, then set that to an instance variable to render in the template.

Something like:
```
    def call(params)
      @books = Books::IndexBooks.new.call.list
    end
```

Does that help?

**Comment by 256hax** [comment]
@cllns Thank you so much!! I could fix that!
