### ISSUE TITLE
ROM::Registry::ElementNotFoundError:

### ISSUE THREAD

**Issue by bcaccinolo** [hanami/hanami#938]
Hello,
I have a problem with Hanami using nested aggregates like this:

```ruby
case_id = 42
case_repo = CaseRepository.new
case_repo.aggregate(changes: :change_type).where(id: case_id).as(Case).one
```

I get the error:

```
ROM::Registry::ElementNotFoundError: :change_types doesn't exist in ROM::RelationRegistry registry
	from /usr/local/bundle/gems/rom-3.3.3/lib/rom/registry.rb:35:in `block in fetch'
	from /usr/local/bundle/gems/rom-3.3.3/lib/rom/registry.rb:32:in `fetch'
	from /usr/local/bundle/gems/rom-3.3.3/lib/rom/registry.rb:32:in `fetch'
	from /usr/local/bundle/gems/rom-repository-1.4.0/lib/rom/repository/relation_proxy/combine.rb:255:in `combine_opts_for_assoc'
	from /usr/local/bundle/gems/rom-repository-1.4.0/lib/rom/repository/relation_proxy/combine.rb:86:in `block in combine'
	from /usr/local/bundle/gems/rom-repository-1.4.0/lib/rom/repository/relation_proxy/combine.rb:59:in `each'
	from /usr/local/bundle/gems/rom-repository-1.4.0/lib/rom/repository/relation_proxy/combine.rb:59:in `combine'
	from /usr/local/bundle/gems/rom-repository-1.4.0/lib/rom/repository/relation_proxy/combine.rb:256:in `combine_opts_for_assoc'
	from /usr/local/bundle/gems/rom-repository-1.4.0/lib/rom/repository/relation_proxy/combine.rb:86:in `block in combine'
	from /usr/local/bundle/gems/rom-repository-1.4.0/lib/rom/repository/relation_proxy/combine.rb:59:in `each'
	from /usr/local/bundle/gems/rom-repository-1.4.0/lib/rom/repository/relation_proxy/combine.rb:59:in `combine'
	from /usr/local/bundle/gems/rom-repository-1.4.0/lib/rom/repository/root.rb:103:in `block in aggregate'
	from /usr/local/bundle/gems/rom-repository-1.4.0/lib/rom/repository/root.rb:103:in `each'
	from /usr/local/bundle/gems/rom-repository-1.4.0/lib/rom/repository/root.rb:103:in `reduce'
	from /usr/local/bundle/gems/rom-repository-1.4.0/lib/rom/repository/root.rb:103:in `aggregate'
	from (irb):4
```

But this works fine:
```ruby
case_id = 42
case_repo = CaseRepository.new
case_repo.aggregate(:changes).where(id: case_id).as(Case).one
```

and this also:
```ruby
ct_id = 42
change_repo = ChangeRepository.new
change_repo.aggregate(:change_type).where(id: ct_id).as(ChangeType).one
```

## Repositories

```ruby
class CaseRepository < Hanami::Repository
  associations do
    has_many :changes
  end
end
```

```ruby
class ChangeRepository < Hanami::Repository
  associations do
    belongs_to :case
    belongs_to :change_type
  end
end
```

```ruby
class ChangeTypeRepository < Hanami::Repository
  associations do
    has_many :changes
  end
end
```

## Notice

This is not a vanilla Hanami project.
It's a Rails 4 app with Hanami model & validation included in.

Gemfile
```
...
gem 'hanami-model', '1.2.0'
gem 'hanami-validations', '1.2.0'
...
```

Repositories are loaded like this:
```
require "hanami/model"
require 'hanami/model/sql'

require_relative 'repositories/change_type_repository'
require_relative 'repositories/change_repository'
require_relative 'repositories/case_repository'
```

/benoit

**Comment by jodosha** [comment]
@bcaccinolo I'm happy that you found the solution. Happy coding!
