### ISSUE TITLE
Can't insert data when using string key

### ISSUE THREAD

**Issue by vsanta** [hanami/hanami#983]
Hello,

I just started exploring Hanami today and was playing around, creating a simple JSON API. 

The controller is super simple, it is getting the post data and calling the repository to create a new record.
```
 def call(params)
      cat = JSON.parse(request.body.read)
      new_cat = CatRepository.new.create(cat["cat"])

      self.data = new_cat
    end
```

This fails with;
```
SQLite3::ConstraintException: NOT NULL constraint failed: cats.name: INSERT INTO `cats` (`created_at`, `updated_at`) VALUES ('2019-01-24 21:42:41.838856', '2019-01-24 21:42:41.838856')
Hanami::Model::NotNullConstraintViolationError: SQLite3::ConstraintException: NOT NULL constraint failed: cats.name
```

I continued to explore and tried to use hardcoded data in the console and it seems that when the param passed on the `create` is a Hash with ta string as the key it fails but works with symbols.

Here is the example I ran:
```
cat1 = {name: "Fluffy" }
cat2 = {"name"=>"Fluffier"}

CatRepository.new.create cat1
[cats] [INFO] [2019-01-24 16:51:30 -0500] (0.008500s) INSERT INTO `cats` (`name`, `created_at`, `updated_at`) VALUES ('Fluffy', '2019-01-24 21:51:30.564175', '2019-01-24 21:51:30.564175')
[cats] [INFO] [2019-01-24 16:51:30 -0500] (0.000532s) SELECT `id`, `name`, `created_at`, `updated_at` FROM `cats` WHERE (`id` IN (6)) ORDER BY `cats`.`id`
 => #<Cat:0x007fdfe1981d40 @attributes={:id=>6, :name=>"Fluffy", :created_at=>2019-01-24 21:51:30 UTC, :updated_at=>2019-01-24 21:51:30 UTC}>
2.4.1 :013 >

CatRepository.new.create cat2
[cats] [ERROR] [2019-01-24 16:51:50 -0500] SQLite3::ConstraintException: NOT NULL constraint failed: cats.name: INSERT INTO `cats` (`created_at`, `updated_at`) VALUES ('2019-01-24 21:51:50.234913', '2019-01-24 21:51:50.234913')
Hanami::Model::NotNullConstraintViolationError: SQLite3::ConstraintException: NOT NULL constraint failed: cats.name
	from /Users/vanessasantanna/.rvm/gems/ruby-2.4.1/gems/hanami-model-1.3.1/lib/hanami/repository.rb:362:in `rescue in create'
	from /Users/vanessasantanna/.rvm/gems/ruby-2.4.1/gems/hanami-model-1.3.1/lib/hanami/repository.rb:360:in `create'
	from (irb):13
	from /Users/vanessasantanna/.rvm/gems/ruby-2.4.1/gems/hanami-1.3.1/lib/hanami/cli/commands/console.rb:51:in `call'
	from /Users/vanessasantanna/.rvm/gems/ruby-2.4.1/gems/hanami-1.3.1/lib/hanami/cli/commands/command.rb:85:in `call'
	from /Users/vanessasantanna/.rvm/gems/ruby-2.4.1/gems/hanami-cli-0.3.1/lib/hanami/cli.rb:57:in `call'
	from /Users/vanessasantanna/.rvm/gems/ruby-2.4.1/gems/hanami-1.3.1/bin/hanami:6:in `<top (required)>'
	from /Users/vanessasantanna/.rvm/gems/ruby-2.4.1/bin/hanami:23:in `load'
	from /Users/vanessasantanna/.rvm/gems/ruby-2.4.1/bin/hanami:23:in `<main>'
	from /Users/vanessasantanna/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/vanessasantanna/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```
Not sure if I'm doing anything wrong. I also haven't done Ruby in 4 years so :)

Hope someone can help.

**Comment by jodosha** [comment]
@vsanta Hello, why did you close the ticket? Did you figure out? Would you mind to share the solution here? So other people would benefit from your experience. Thanks.
